# Data understanding

In [473]:
# importing libraries
import pandas as pd
import sqlite3

In [474]:
# loading data sets
bom_df= pd.read_csv("data/bom.movie_gross.csv")
rt_reviews_df=pd.read_csv("data/rt.reviews.tsv", sep= '\t', encoding= 'latin1') 
rt_movie_info_df= pd.read_csv("data/rt.movie_info.tsv", sep= '\t', encoding= 'latin1')
tmdb_movies_df= pd.read_csv("data/tmdb.movies.csv")
tn_movie_budgets_df= pd.read_csv("data/tn.movie_budgets.csv")

# previewing each
for name, df in [('Box office mojo', bom_df), ('Rotten tomatoes Reviews', rt_reviews_df), ('Rotten tomatoes movie info', rt_movie_info_df),
                 ('The movie DB',tmdb_movies_df), ('The numbers', tn_movie_budgets_df)]:
    print(f"\n{name} Sample:")
    print(df.head())
    print(df.info())

Box office mojo Sample:
                                         title studio  domestic_gross  \
0                                  Toy Story 3     BV     415000000.0
1                   Alice in Wonderland (2010)     BV     334200000.0
2  Harry Potter and the Deathly Hallows Part 1     WB     296000000.0
3                                    Inception     WB     292600000.0
4                          Shrek Forever After   P/DW     238700000.0

  foreign_gross  year
0     652000000  2010
1     691300000  2010
2     664300000  2010
3     535700000  2010
4     513900000  2010
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3387 entries, 0 to 3386
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   title           3387 non-null   object
 1   studio          3382 non-null   object
 2   domestic_gross  3359 non-null   float64
 3   foreign_gross   2037 non-null   object
 4   year            3387 non-null   int64
dtypes: float64(1), int64(1), object(3)
memory usage: 132.4+ KB
None

Rotten tomatoes Reviews Sample:
   id                                             review rating   fresh  \
0   3  A distinctly gallows take on contemporary fina...    3/5   fresh
1   3  It's an allegory in search of a meaning that n...    NaN  rotten
2   3  ... life lived in a bubble in financial dealin...    NaN   fresh
3   3  Continuing along a line introduced in last yea...    NaN   fresh
4   3             ... a perverse twist on neorealism...     NaN   fresh

           critic  top_critic         publisher               date
0      PJ Nabarro           0   Patrick Nabarro  November 10, 2018
1  Annalee Newitz           0           io9.com       May 23, 2018
2    Sean Axmaker           0  Stream on Demand    January 4, 2018
3   Daniel Kasman           0              MUBI  November 16, 2017
4             NaN           0      Cinema Scope   October 12, 2017
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54432 entries, 0 to 54431
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          54432 non-null  int64
 1   review      48869 non-null  object
 2   rating      40915 non-null  object
 3   fresh       54432 non-null  object
 4   critic      51710 non-null  object
 5   top_critic  54432 non-null  int64
 6   publisher   54123 non-null  object
 7   date        54432 non-null  object
dtypes: int64(2), object(6)
memory usage: 3.3+ MB
None

Rotten tomatoes movie info Sample:
   id                                           synopsis rating  \
0   1  This gritty, fast-paced, and innovative police...      R
1   3  New York City, not-too-distant-future: Eric Pa...      R
2   5  Illeana Douglas delivers a superb performance ...      R
3   6  Michael Douglas runs afoul of a treacherous su...      R
4   7                                                NaN     NR

                                 genre          director  \
0  Action and Adventure|Classics|Drama  William Friedkin
1    Drama|Science Fiction and Fantasy  David Cronenberg
2    Drama|Musical and Performing Arts    Allison Anders
3           Drama|Mystery and Suspense    Barry Levinson
4                        Drama|Romance    Rodney Bennett

                            writer  theater_date      dvd_date currency  \
0                   Ernest Tidyman   Oct 9, 1971  Sep 25, 2001      NaN
1     David Cronenberg|Don DeLillo  Aug 17, 2012   Jan 1, 2013        $
2                   Allison Anders  Sep 13, 1996  Apr 18, 2000      NaN
3  Paul Attanasio|Michael Crichton   Dec 9, 1994  Aug 27, 1997      NaN
4                     Giles Cooper           NaN           NaN      NaN

  box_office      runtime             studio
0        NaN  104 minutes                NaN
1    600,000  108 minutes  Entertainment One
2        NaN  116 minutes                NaN
3        NaN  128 minutes                NaN
4        NaN  200 minutes                NaN
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1560 entries, 0 to 1559
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            1560 non-null   int64
 1   synopsis      1498 non-null   object
 2   rating        1557 non-null   object
 3   genre         1552 non-null   object
 4   director      1361 non-null   object
 5   writer        1111 non-null   object
 6   theater_date  1201 non-null   object
 7   dvd_date      1201 non-null   object
 8   currency      340 non-null    object
 9   box_office    340 non-null    object
 10  runtime       1530 non-null   object
 11  studio        494 non-null    object
dtypes: int64(1), object(11)
memory usage: 146.4+ KB
None

The movie DB Sample:
   Unnamed: 0            genre_ids     id original_language  \
0           0      [12, 14, 10751]  12444                en
1           1  [14, 12, 16, 10751]  10191                en
2           2        [12, 28, 878]  10138                en
3           3      [16, 35, 10751]    862                en
4           4        [28, 878, 12]  27205                en

                                 original_title  popularity release_date  \
0  Harry Potter and the Deathly Hallows: Part 1      33.533   2010-11-19
1                      How to Train Your Dragon      28.734   2010-03-26
2                                    Iron Man 2      28.515   2010-05-07
3                                     Toy Story      28.005   1995-11-22
4                                     Inception      27.920   2010-07-16

                                          title  vote_average  vote_count
0  Harry Potter and the Deathly Hallows: Part 1           7.7       10788
1                      How to Train Your Dragon           7.7        7610
2                                    Iron Man 2           6.8       12368
3                                     Toy Story           7.9       10174
4                                     Inception           8.3       22186
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26517 entries, 0 to 26516
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         26517 non-null  int64
 1   genre_ids          26517 non-null  object
 2   id                 26517 non-null  int64
 3   original_language  26517 non-null  object
 4   original_title     26517 non-null  object
 5   popularity         26517 non-null  float64
 6   release_date       26517 non-null  object
 7   title              26517 non-null  object
 8   vote_average       26517 non-null  float64
 9   vote_count         26517 non-null  int64
dtypes: float64(2), int64(3), object(5)
memory usage: 2.0+ MB
None

The numbers Sample:
   id  release_date                                        movie  \
0   1  Dec 18, 2009                                       Avatar
1   2  May 20, 2011  Pirates of the Caribbean: On Stranger Tides
2   3   Jun 7, 2019                                 Dark Phoenix
3   4   May 1, 2015                      Avengers: Age of Ultron
4   5  Dec 15, 2017            Star Wars Ep. VIII: The Last Jedi

  production_budget domestic_gross worldwide_gross
0      $425,000,000   $760,507,625  $2,776,345,279
1      $410,600,000   $241,063,875  $1,045,663,875
2      $350,000,000    $42,762,350    $149,762,350
3      $330,600,000   $459,005,868  $1,403,013,963
4      $317,000,000   $620,181,382  $1,316,721,747
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5782 entries, 0 to 5781
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 5782 non-null   int64
 1   release_date       5782 non-null   object
 2   movie              5782 non-null   object
 3   production_budget  5782 non-null   object
 4   domestic_gross     5782 non-null   object
 5   worldwide_gross    5782 non-null   object
dtypes: int64(1), object(5)
memory usage: 271.2+ KB
None

## Data understanding of each dataframe

In [475]:
#Box office mojo dataset(movie_gross)
# checking the shape
bom_df= pd.read_csv("data/bom.movie_gross.csv")
bom_df.shape

(3387, 5)

bom_df dataframe from Box office Mojo has 3387 records and 5 columns.

In [476]:
# checking the info
bom_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3387 entries, 0 to 3386
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   title           3387 non-null   object
 1   studio          3382 non-null   object
 2   domestic_gross  3359 non-null   float64
 3   foreign_gross   2037 non-null   object
 4   year            3387 non-null   int64
dtypes: float64(1), int64(1), object(3)
memory usage: 132.4+ KB

## Observation

Total rows: 3387 movies

Columns: 5 - title, studio, domestic_gross, foreign_gross and year.

The dataset is mostly complete with title and year having no missing values

The column with more missing values is foreign_gross followed by domestic_gross and lastly studio.

foreign_gross is stored as object instead of float, likely due to formatting issues.

In [477]:
# reviewing Rotten Tomatoes dataset(reviews df)
rt_reviews_df=pd.read_csv("data/rt.reviews.tsv", sep= '\t', encoding= 'latin1') 
rt_reviews_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54432 entries, 0 to 54431
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          54432 non-null  int64
 1   review      48869 non-null  object
 2   rating      40915 non-null  object
 3   fresh       54432 non-null  object
 4   critic      51710 non-null  object
 5   top_critic  54432 non-null  int64
 6   publisher   54123 non-null  object
 7   date        54432 non-null  object
dtypes: int64(2), object(6)
memory usage: 3.3+ MB

In [478]:
# checking missing values
rt_reviews_df.isna().sum()

id                0
review         5563
rating        13517
fresh             0
critic         2722
top_critic        0
publisher       309
date              0
dtype: int64

## Observation

Total rows: 54,432 reviews

Columns: 8 including id, review, rating, fresh, critic, top_critic, publisher, and date

All rows have id, fresh, top_critic, and date

missing values are significant in some columns

- review: 5563 missing values

- rating: 13517 missing

- rating: 13517 missing

- publisher: 309 missing values

Date column can be converted to date-time format

In [479]:
# reviewing Rotten Tomatoes dataset(movie_info)
rt_movie_info_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1560 entries, 0 to 1559
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            1560 non-null   int64
 1   synopsis      1498 non-null   object
 2   rating        1557 non-null   object
 3   genre         1552 non-null   object
 4   director      1361 non-null   object
 5   writer        1111 non-null   object
 6   theater_date  1201 non-null   object
 7   dvd_date      1201 non-null   object
 8   currency      340 non-null    object
 9   box_office    340 non-null    object
 10  runtime       1530 non-null   object
 11  studio        494 non-null    object
dtypes: int64(1), object(11)
memory usage: 146.4+ KB

In [480]:
rt_movie_info_df.isna().sum()

id                 0
synopsis          62
rating             3
genre              8
director         199
writer           449
theater_date     359
dvd_date         359
currency        1220
box_office      1220
runtime           30
studio          1066
dtype: int64

## Observation
Total rows: 1560 movie reviews
    
Columns: 12- id, synopsis, rating, genre, director, writer, theater_date, dvd_date, currency, box_office, runtime, studio

Columns like id, rating, genre, and runtime are mostly complete.

Missing values are significant in several columns

- synopsis: 62 missing

- director: 199 missing

- writer: 449 missing

- theater_date and dvd_date: both have 359 missing

- box_office and currency: 1220 missing

- studio: 1066 missing, most data missing

Theater_date, dvd_date, and runtime should be converted to datetime or numeric for analysis.

box_office and currency are object types need to be converted to numeric

In [481]:
#  reviewing the movie DB dataset(tmdb_movie df)
tmdb_movies_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26517 entries, 0 to 26516
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         26517 non-null  int64
 1   genre_ids          26517 non-null  object
 2   id                 26517 non-null  int64
 3   original_language  26517 non-null  object
 4   original_title     26517 non-null  object
 5   popularity         26517 non-null  float64
 6   release_date       26517 non-null  object
 7   title              26517 non-null  object
 8   vote_average       26517 non-null  float64
 9   vote_count         26517 non-null  int64
dtypes: float64(2), int64(3), object(5)
memory usage: 2.0+ MB

## Observation

Total movies: 26,517

Columns: 10 - includes title info, ratings, language, and release_date
    
No missing values across any of the 10 columns - very clean.

unnamed column needs to be dropped

release_date should be converted to datetime

In [482]:
# reviewing The Numbers dataset(movie_budgets df)
tn_movie_budgets_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5782 entries, 0 to 5781
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 5782 non-null   int64
 1   release_date       5782 non-null   object
 2   movie              5782 non-null   object
 3   production_budget  5782 non-null   object
 4   domestic_gross     5782 non-null   object
 5   worldwide_gross    5782 non-null   object
dtypes: int64(1), object(5)
memory usage: 271.2+ KB

## Observation

Total entries: 5,782 movies

Columns: 6 - focused on financial and release information

Complete data (no missing entries) across all columns

Key financial metrics included:

- production_budget

- domestic_gross

- worldwide_gross

release_date is present, enabling time-based trend analysis

In [483]:
# loading the sqlite database
con= sqlite3.connect("data/im.db") #creating a connection

# previewing the schema
pd.read_sql("""
SELECT name
FROM sqlite_master
WHERE type= "table";
""", con)

            name
0   movie_basics
1      directors
2      known_for
3     movie_akas
4  movie_ratings
5        persons
6     principals
7        writers

In [484]:
# selecting movie_basics and movie_ratings tables
query= """
SELECT *
FROM movie_basics

"""
pd.read_sql(query, con).tail()

,movie_id,primary_title,original_title,start_year,runtime_minutes,genres
146139,tt9916538,Kuambil Lagi Hatiku,Kuambil Lagi Hatiku,2019,123.0,Drama
146140,tt9916622,Rodolpho Teóphilo - O Legado de um Pioneiro,Rodolpho Teóphilo - O Legado de um Pioneiro,2015,NaN,Documentary
146141,tt9916706,Dankyavar Danka,Dankyavar Danka,2013,NaN,Comedy
146142,tt9916730,6 Gunn,6 Gunn,2017,116.0,None
146143,tt9916754,Chico Albuquerque - Revelações,Chico Albuquerque - Revelações,2013,NaN,Documentary

In [485]:
query= """
SELECT *
FROM movie_ratings
"""
pd.read_sql(query, con).tail()

        movie_id  averagerating  numvotes
73851  tt9805820            8.1        25
73852  tt9844256            7.5        24
73853  tt9851050            4.7        14
73854  tt9886934            7.0         5
73855  tt9894098            6.3       128

In [486]:
# joining the two tables using movie_id
query= """
SELECT *
FROM movie_basics
LEFT JOIN movie_ratings
USING(movie_id);
"""
movie_basics_rating_df= pd.read_sql(query, con)
movie_basics_rating_df.tail()

,movie_id,primary_title,original_title,start_year,runtime_minutes,genres,averagerating,numvotes
146139,tt9916538,Kuambil Lagi Hatiku,Kuambil Lagi Hatiku,2019,123.0,Drama,NaN,NaN
146140,tt9916622,Rodolpho Teóphilo - O Legado de um Pioneiro,Rodolpho Teóphilo - O Legado de um Pioneiro,2015,NaN,Documentary,NaN,NaN
146141,tt9916706,Dankyavar Danka,Dankyavar Danka,2013,NaN,Comedy,NaN,NaN
146142,tt9916730,6 Gunn,6 Gunn,2017,116.0,None,NaN,NaN
146143,tt9916754,Chico Albuquerque - Revelações,Chico Albuquerque - Revelações,2013,NaN,Documentary,NaN,NaN

# Data cleaning

## Box office mojo dataset

In [487]:
# creating a working copy 
bom_clean_df= bom_df.copy()

In [488]:
bom_clean_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3387 entries, 0 to 3386
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   title           3387 non-null   object
 1   studio          3382 non-null   object
 2   domestic_gross  3359 non-null   float64
 3   foreign_gross   2037 non-null   object
 4   year            3387 non-null   int64
dtypes: float64(1), int64(1), object(3)
memory usage: 132.4+ KB

In [489]:
# checking for duplicates
duplicated_rows= bom_clean_df.duplicated()
duplicated_rows.sum()

0

In [490]:
# cleaning the bom_df(movie_gross) from Box office mojo dataset
bom_clean_df.columns

Index(['title', 'studio', 'domestic_gross', 'foreign_gross', 'year'], dtype='object')

In [491]:
# cleaning title column
# checking for duplicates
key_columns= ['title', 'year']
dupl_row= bom_clean_df[bom_clean_df.duplicated(subset= key_columns, keep= False)]
dupl_row

Empty DataFrame
Columns: [title, studio, domestic_gross, foreign_gross, year]
Index: []

There are no duplicates

In [492]:
bom_clean_df.isna().sum()

title                0
studio               5
domestic_gross      28
foreign_gross     1350
year                 0
dtype: int64

In [493]:
# cleaning studio column
bom_clean_df['studio'] = bom_clean_df['studio'].str.strip()

In [494]:
# checking for missing values 
missing_studio = bom_clean_df['studio'].isnull().sum()
missing_studio

# filling in missing values
bom_clean_df['studio']= bom_clean_df['studio'].fillna("unknown")

In [495]:
# checking for missing values
bom_clean_df['studio'].isnull().sum()

0

In [496]:
missing_domestic_gross = bom_clean_df[bom_clean_df['domestic_gross'].isna()]
# Print the rows with missing domestic_gross
print("\nRows with missing domestic_gross:")
print(missing_domestic_gross[['title', 'studio', 'domestic_gross', 'foreign_gross', 'year']])

Rows with missing domestic_gross:
                                      title   studio  domestic_gross  \
230              It's a Wonderful Afterlife      UTV             NaN
298   Celine: Through the Eyes of the World     Sony             NaN
302                              White Lion    Scre.             NaN
306                        Badmaash Company     Yash             NaN
327                      Aashayein (Wishes)  Relbig.             NaN
537                                   Force     FoxS             NaN
713                        Empire of Silver     NeoC             NaN
871                            Solomon Kane     RTWC             NaN
928                            The Tall Man    Imag.             NaN
933                   Keith Lemon: The Film  unknown             NaN
936                     Lula, Son of Brazil     NYer             NaN
966                          The Cup (2012)     Myr.             NaN
1017                              Dark Tide      WHE             NaN
1079                         The Green Wave       RF             NaN
1268                             22 Bullets    Cdgm.             NaN
1308             Matru Ki Bijlee Ka Mandola      FIP             NaN
1340                      The Snitch Cartel       PI             NaN
1342           All the Boys Love Mandy Lane     RTWC             NaN
1368                                6 Souls     RTWC             NaN
1659                             Jessabelle      LGF             NaN
1681                              14 Blades     RTWC             NaN
1685        Jack and the Cuckoo-Clock Heart   Shout!             NaN
1739                              Lila Lila    Crnth             NaN
1975         Surprise - Journey To The West       AR             NaN
2392                    Finding Mr. Right 2       CL             NaN
2468                                 Solace      LGP             NaN
2595                                  Viral   W/Dim.             NaN
2825                       Secret Superstar  unknown             NaN

     foreign_gross  year
230        1300000  2010
298         119000  2010
302          99600  2010
306          64400  2010
327           3800  2010
537        4800000  2011
713          19000  2011
871       19600000  2012
928        5200000  2012
933        4000000  2012
936        3800000  2012
966        1800000  2012
1017        432000  2012
1079         70100  2012
1268      21300000  2013
1308       6000000  2013
1340       2100000  2013
1342       1900000  2013
1368        852000  2013
1659       7000000  2014
1681       3800000  2014
1685       3400000  2014
1739       1100000  2014
1975      49600000  2015
2392     114700000  2016
2468      22400000  2016
2595        552000  2016
2825     122000000  2017

In [497]:
# filling in missing values with mean
mean= bom_clean_df['domestic_gross'].mean()
bom_clean_df['domestic_gross']= bom_clean_df['domestic_gross'].fillna(mean)


# checking for null
bom_clean_df['domestic_gross'].isnull().sum()

0

In [498]:
# cleaning year column
bom_clean_df["year"].dtype

dtype('int64')

In [499]:
# cleaning foreign column
bom_clean_df['foreign_gross'].isnull().sum()

1350

In [500]:
# dropping foreign_gross column
bom_clean_df.drop(columns= 'foreign_gross', inplace= True)

## Cleaning Rotten Tomatoes reviews dataset

In [501]:
# creating a copy
rt_reviews_clean_df=rt_reviews_df.copy()

In [502]:
# missing values
rt_reviews_clean_df.isna().sum()

id                0
review         5563
rating        13517
fresh             0
critic         2722
top_critic        0
publisher       309
date              0
dtype: int64

In [503]:
# checking for id duplicates
duplicate_count = rt_reviews_clean_df.duplicated().sum()
print(f"Number of duplicates: {duplicate_count}")

Number of duplicates: 9

In [504]:
# checking for duplicates while focusing on specific columns for clarity
if all(col in rt_reviews_clean_df for col in ['id', 'review', 'critic','publisher', 'date']):
        initial_rows_rt_reviews = len(rt_reviews_clean_df)
        rt_reviews_clean_df.drop_duplicates(subset=['id', 'review', 'critic','publisher', 'date'])
        print(f"rt_reviews_clean_df: Removed {initial_rows_rt_reviews - len(rt_reviews_clean_df)} duplicates based on 'id', 'review','publisher', 'critic', and 'date'.")
else:
        print("rt_reviews_clean_df: Skipping duplicate check due to missing 'id', 'review', 'critic', or 'date' columns.")

rt_reviews_clean_df: Removed 0 duplicates based on 'id', 'review','publisher', 'critic', and 'date'.

In [505]:
# checking for columns unique values in each column
for column in rt_reviews_clean_df.columns:
    print(f"\n{column} unique values:")
    print(rt_reviews_df[column].unique())

id unique values:
[   3    5    6 ... 1998 1999 2000]

review unique values:
["A distinctly gallows take on contemporary financial mores, as one absurdly rich man's limo ride across town for a haircut functions as a state-of-the-nation discourse. "
 "It's an allegory in search of a meaning that never arrives...It's just old-fashioned bad storytelling."
 '... life lived in a bubble in financial dealings and digital communications and brief face-to-face conversations and sexual intermissions in a space shuttle of a limousine creeping through the gridlock of an anonymous New York City.'
 ...
 "Despite Besson's high-profile name being Wasabi's big selling point, there is no doubt that Krawczyk deserves a huge amount of the credit for the film's thoroughly winning tone."
 'The film lapses too often into sugary sentiment and withholds delivery on the pell-mell pyrotechnics its punchy style promises.'
 'The real charm of this trifle is the deadpan comic face of its star, Jean Reno, who resembles Sly Stallone in a hot sake half-sleep.']

rating unique values:
['3/5' nan 'C' '2/5' 'B-' '2/4' 'B' '3/4' '4/5' '4/4' '6/10' '1/4' '8'
 '2.5/4' '4/10' '2.0/5' '3/10' '7/10' 'A-' '5/5' 'F' '3.5/4' 'D+' '1.5/4'
 '3.5/5' '8/10' 'B+' '9/10' '2.5/5' '7.5/10' '5.5/10' 'C-' '1.5/5' '1/5'
 '5/10' 'C+' '0/5' '6' '0.5/4' 'D' '3.1/5' '3/6' '4.5/5' '0/4' '2/10' 'D-'
 '7' '1/10' '3' 'A+' 'A' '4.0/4' '9.5/10' '2.5' '2.1/2' '6.5/10' '3.7/5'
 '8.4/10' '9' '1' '7.2/10' '2.2/5' '0.5/10' '5' '0' '2' '4.5' '7.7'
 '5.0/5' '8.5/10' '3.0/5' '0.5/5' '1.5/10' '3.0/4' '2.3/10' '4.5/10' '4/6'
 '3.5' '8.6/10' '6/8' '2.0/4' '2.7' '4.2/10' '5.8' '4' '7.1/10' '5/4' 'N'
 '3.5/10' '5.8/10' 'R' '4.0/5' '0/10' '5.0/10' '5.9/10' '2.4/5' '1.9/5'
 '4.9' '7.4/10' '1.5' '2.3/4' '8.8/10' '4.0/10' '2.2' '3.8/10' '6.8/10'
 '7.3' '7.0/10' '3.2' '4.2' '8.4' '5.5/5' '6.3/10' '7.6/10' '8.1/10'
 '3.6/5' '2/6' '7.7/10' '1.8' '8.9/10' '8.9' '8.2/10' '8.3/10' '2.6/6'
 '4.1/10' '2.5/10' 'F+' '6.0/10' '1.0/4' '7.9/10' '8.7/10' '4.3/10'
 '9.6/10' '9.0/10' '4.0' '1.7' '7.9' '6.7' '8.0/10' '9.2/10' '5.2' '5.9'
 '3.7' '4.7' '6.2/10' '1/6' '8.2' '2.6/5' '3.4' '9.7' '3.3/5' '3.8/5'
 '1/2' '7.4' '4.8' '1.6/5' '2/2' '1-5' '1.0' '4.3/5' '5/6' '9.2' '2.7/5'
 '4.9/10' '3.0' '3.1' '7.8/10' 'F-' '2.3/5' '3.0/10' '3/2' '7.8' '4.2/5'
 '9.0' '7.3/10' '4.4/5' '6.9/10' '0/6' 'T' '6.2' '3.3' '9.8' '8.5' '1.0/5'
 '4.1' '7.1' '3 1/2']

fresh unique values:
['fresh' 'rotten']

critic unique values:
['PJ Nabarro' 'Annalee Newitz' 'Sean Axmaker' ... 'Raam Tarat'
 'Jeremy Conrad' 'Bob Cannon']

top_critic unique values:
[0 1]

publisher unique values:
['Patrick Nabarro' 'io9.com' 'Stream on Demand' ...
 'The Big Issue (Australia)' 'The Jacobin' 'OZY']

date unique values:
['November 10, 2018' 'May 23, 2018' 'January 4, 2018' ... 'May 27, 2007'
 'August 20, 2006' 'April 1, 1993']

In [506]:
# filling in review column
if 'review' in rt_reviews_clean_df.columns:
    missing_review_count= rt_reviews_clean_df['review'].isna().sum()
    if missing_review_count >0:
        rt_reviews_clean_df['review']= rt_reviews_clean_df['review'].fillna('No Review Text')
        print(f"Filled {missing_review_count} missing 'review' values with 'No Review Text'.")

Filled 5563 missing 'review' values with 'No Review Text'.

In [507]:
# dropping unuseful columns
rt_reviews_clean_df.drop(columns=['rating'], inplace=True)

In [508]:
# checking if the columns are dropped
rt_reviews_clean_df.columns

Index(['id', 'review', 'fresh', 'critic', 'top_critic', 'publisher', 'date'], dtype='object')

In [509]:
# filling critic column missing values with unknown
rt_reviews_clean_df['critic']= rt_reviews_clean_df['critic'].fillna("Unknown")

In [510]:
# filling publisher missing with unknown
rt_reviews_clean_df['publisher']= rt_reviews_clean_df['publisher'].fillna("Unknown")

In [511]:
# converting date into datetime format
rt_reviews_clean_df['date'] = pd.to_datetime(rt_reviews_clean_df['date'])

# checking effectiveness
rt_reviews_clean_df["date"].dtype

dtype('<M8[ns]')

In [512]:
# checking missing values in the df
rt_reviews_clean_df.isna().sum()

id            0
review        0
fresh         0
critic        0
top_critic    0
publisher     0
date          0
dtype: int64

## Cleaning Rotten Tomatoes movie info dataset

In [513]:
# creating a working copy
rt_movie_info_clean= rt_movie_info_df.copy()

In [514]:
# checking for missing values
rt_movie_info_clean.isnull().sum()

id                 0
synopsis          62
rating             3
genre              8
director         199
writer           449
theater_date     359
dvd_date         359
currency        1220
box_office      1220
runtime           30
studio          1066
dtype: int64

In [515]:
# checking for columns unique values in each column
for column in rt_movie_info_clean.columns:
    print(f"\n{column} unique values:")
    print(rt_movie_info_clean[column].unique())

id unique values:
[   1    3    5 ... 1998 1999 2000]

synopsis unique values:
['This gritty, fast-paced, and innovative police drama earned five Academy Awards, including Best Picture, Best Adapted Screenplay (written by Ernest Tidyman), and Best Actor (Gene Hackman). Jimmy "Popeye" Doyle (Hackman) and his partner, Buddy Russo (Roy Scheider), are New York City police detectives on narcotics detail, trying to track down the source of heroin from Europe into the United States. Suave Alain Charnier (Fernando Rey) is the French drug kingpin who provides a large percentage of New York City\'s dope, and Pierre Nicoli (Marcel Bozzuffi) is a hired killer and Charnier\'s right-hand man. Acting on a hunch, Popeye and Buddy start tailing Sal Boca (Tony Lo Bianco) and his wife, Angie (Arlene Faber), who live pretty high for a couple whose corner store brings in about 7,000 dollars a year. It turns out Popeye\'s suspicions are right -- Sal and Angie are the New York agents for Charnier, who will be smuggling 32 million dollars\' worth of heroin into the city in a car shipped over from France. The French Connection broke plenty of new ground for screen thrillers; Popeye Doyle was a highly unusual "hero," an often violent, racist, and mean-spirited cop whose dedication to his job fell just short of dangerous obsession. The film\'s high point, a high-speed car chase with Popeye tailing an elevated train, was one of the most viscerally exciting screen moments of its day and set the stage for dozens of action sequences to follow. And the film\'s grimy realism (and downbeat ending) was a big change from the buff-and-shine gloss and good-guys-always-win heroics of most police dramas that preceded it. The French Connection was inspired by a true story, and Eddie Egan and Sonny Grosso, Popeye and Buddy\'s real life counterparts, both have small roles in the film. A sequel followed four years later.'
 "New York City, not-too-distant-future: Eric Packer, a 28 year-old finance golden boy dreaming of living in a civilization ahead of this one, watches a dark shadow cast over the firmament of the Wall Street galaxy, of which he is the uncontested king. As he is chauffeured across midtown Manhattan to get a haircut at his father's old barber, his anxious eyes are glued to the yuan's exchange rate: it is mounting against all expectations, destroying Eric's bet against it. Eric Packer is losing his empire with every tick of the clock. Meanwhile, an eruption of wild activity unfolds in the city's streets. Petrified as the threats of the real world infringe upon his cloud of virtual convictions, his paranoia intensifies during the course of his 24-hour cross-town odyssey. Packer starts to piece together clues that lead him to a most terrifying secret: his imminent assassination. -- (C) Official Site"
 'Illeana Douglas delivers a superb performance as Denise Waverly, a fictional singer and songwriter whose life bears more than a passing resemblance to that of real-life pop star Carole King. Edna Buxton, the daughter of a Philadelphia steel tycoon, aspires to a career as a singer, and when against her mother\'s bidding she sings a sultry version of "Hey There (You With the Stars in Your Eyes)" (instead of Mom\'s choice, "You\'ll Never Walk Alone") at a talent contest, she wins a recording contact and moves to New York City. She cuts a record and gains a new stage name, Denise Waverly; however, she soon finds that girl singers are a dime a dozen in the Big Apple and her career as a vocalist goes nowhere. But she has a knack for writing songs, and eccentric producer Joel Milner (John Turturro) asks her to pen some songs for his upcoming projects. Teamed with Howard Caszatt (Eric Stoltz), a hipster songwriter who wants to express his political and social ideals through pop tunes, she finds both a successful collaborator and husband. While her work with Howard gains Denise writing credits on a string of hit records and respect within the industry, their marriage falls apart, and she becomes involved with Jay Phillips (Matt Dillon), the gifted but unstable leader of a popular West Coast surf music combo. Students of pop music history will have a ball with the various characters modeled after real-life rock legends, and the 1960s-style song score includes numbers written by Joni Mitchell and J. Mascis (of the band Dinosaur Jr.), as well as one-time King collaborator Gerry Goffin; a collaboration between Elvis Costello and Burt Bacharach, "God Give Me Strength," led to a full album written by the two great tunesmiths.'
 ...
 'Based on a novel by Richard Powell, when the lovable (and musical) hillbilly Toby Kwimper (Elvis Presley) and his family move to Florida, they must fight off a group of greedy lowlifes in order to defend the rights to their land. This musical comedy features the songs "Follow That Dream," "Sound Advice," and "What a Wonderful Life."'
 "The Sandlot is a coming-of-age story about a group of young boys growing up in California in 1962. A new, shy boy (Thomas Guiry) moves into the neighborhood, where he is initially rejected by the local boys because he doesn't know how to play baseball. Soon, he learns the sport and joins the group of boys who play ball in a local sandlot, and with his new friends, he has a variety of adventures."
 "Suspended from the force, Paris cop Hubert is summoned to Tokyo when his former lover Miko dies. Upon arriving, Hubert discovers he is to be the legal guardian for Miko's teen daughter Yumi. As Hubert begins to investigate the circumstances surrounding Miko's mysterious death, he grows closer to Yumi."]

rating unique values:
['R' 'NR' 'PG' 'PG-13' nan 'G' 'NC17']

genre unique values:
['Action and Adventure|Classics|Drama' 'Drama|Science Fiction and Fantasy'
 'Drama|Musical and Performing Arts' 'Drama|Mystery and Suspense'
 'Drama|Romance' 'Drama|Kids and Family' 'Comedy' 'Drama'
 'Action and Adventure|Mystery and Suspense|Science Fiction and Fantasy'
 nan 'Documentary' 'Documentary|Special Interest' 'Classics|Comedy|Drama'
 'Comedy|Drama|Mystery and Suspense' 'Action and Adventure|Comedy|Drama'
 'Action and Adventure|Drama|Science Fiction and Fantasy'
 'Art House and International|Comedy|Drama|Musical and Performing Arts'
 'Musical and Performing Arts'
 'Classics|Comedy|Musical and Performing Arts|Romance'
 'Action and Adventure|Drama|Mystery and Suspense'
 'Action and Adventure|Mystery and Suspense'
 'Art House and International|Classics|Horror|Mystery and Suspense'
 'Horror' 'Action and Adventure|Classics|Drama|Mystery and Suspense'
 'Classics|Comedy|Musical and Performing Arts' 'Comedy|Kids and Family'
 'Comedy|Musical and Performing Arts' 'Action and Adventure|Drama|Western'
 'Action and Adventure|Comedy|Mystery and Suspense'
 'Action and Adventure|Drama' 'Mystery and Suspense'
 'Comedy|Drama|Romance' 'Comedy|Drama'
 'Action and Adventure|Science Fiction and Fantasy' 'Comedy|Romance'
 'Art House and International|Drama'
 'Action and Adventure|Drama|Horror|Mystery and Suspense'
 'Comedy|Kids and Family|Romance' 'Classics|Drama' 'Action and Adventure'
 'Action and Adventure|Art House and International|Drama'
 'Comedy|Mystery and Suspense|Science Fiction and Fantasy|Romance'
 'Comedy|Drama|Kids and Family|Romance'
 'Art House and International|Drama|Musical and Performing Arts'
 'Drama|Musical and Performing Arts|Romance'
 'Art House and International|Classics|Horror'
 'Classics|Comedy|Drama|Romance'
 'Art House and International|Drama|Mystery and Suspense|Television'
 'Drama|Sports and Fitness' 'Comedy|Drama|Television'
 'Animation|Kids and Family|Special Interest'
 'Comedy|Drama|Kids and Family'
 'Classics|Comedy|Drama|Kids and Family|Science Fiction and Fantasy'
 'Animation|Comedy|Kids and Family|Science Fiction and Fantasy'
 'Art House and International|Comedy|Drama'
 'Comedy|Science Fiction and Fantasy' 'Classics|Comedy|Special Interest'
 'Action and Adventure|Art House and International|Comedy'
 'Drama|Horror|Mystery and Suspense' 'Art House and International'
 'Action and Adventure|Comedy'
 'Action and Adventure|Animation|Drama|Science Fiction and Fantasy|Special Interest'
 'Action and Adventure|Animation|Art House and International|Drama|Science Fiction and Fantasy'
 'Horror|Mystery and Suspense' 'Classics|Comedy|Romance'
 'Action and Adventure|Art House and International|Drama|Mystery and Suspense'
 'Classics|Drama|Mystery and Suspense|Science Fiction and Fantasy|Romance'
 'Classics|Western|Romance'
 'Art House and International|Drama|Mystery and Suspense'
 'Comedy|Kids and Family|Science Fiction and Fantasy' 'Drama|Television'
 'Classics|Drama|Faith and Spirituality' 'Classics|Comedy'
 'Art House and International|Horror'
 'Action and Adventure|Comedy|Kids and Family'
 'Classics|Drama|Musical and Performing Arts'
 'Action and Adventure|Comedy|Drama|Musical and Performing Arts|Romance'
 'Action and Adventure|Kids and Family|Science Fiction and Fantasy'
 'Drama|Horror|Mystery and Suspense|Television'
 'Art House and International|Comedy|Drama|Romance'
 'Classics|Comedy|Drama|Kids and Family'
 'Classics|Comedy|Drama|Musical and Performing Arts'
 'Art House and International|Classics|Horror|Science Fiction and Fantasy'
 'Horror|Science Fiction and Fantasy'
 'Drama|Horror|Mystery and Suspense|Romance'
 'Action and Adventure|Art House and International|Classics|Drama'
 'Action and Adventure|Classics|Comedy|Musical and Performing Arts|Romance'
 'Documentary|Musical and Performing Arts' 'Action and Adventure|Horror'
 'Comedy|Drama|Musical and Performing Arts' 'Comedy|Horror'
 'Classics|Western'
 'Action and Adventure|Drama|Science Fiction and Fantasy|Television'
 'Art House and International|Drama|Romance'
 'Art House and International|Drama|Horror|Mystery and Suspense|Science Fiction and Fantasy'
 'Classics|Drama|Mystery and Suspense|Science Fiction and Fantasy'
 'Special Interest|Sports and Fitness'
 'Horror|Mystery and Suspense|Science Fiction and Fantasy'
 'Comedy|Horror|Musical and Performing Arts'
 'Action and Adventure|Drama|Kids and Family'
 'Drama|Science Fiction and Fantasy|Romance' 'Comedy|Western'
 'Action and Adventure|Documentary|Science Fiction and Fantasy|Special Interest|Western'
 'Art House and International|Mystery and Suspense'
 'Action and Adventure|Art House and International|Drama|Faith and Spirituality'
 'Classics|Horror' 'Action and Adventure|Classics|Comedy|Drama'
 'Classics|Horror|Mystery and Suspense|Science Fiction and Fantasy'
 'Classics|Documentary|Drama|Romance' 'Action and Adventure|Western'
 'Art House and International|Comedy|Drama|Mystery and Suspense'
 'Musical and Performing Arts|Special Interest'
 'Action and Adventure|Art House and International'
 'Art House and International|Drama|Special Interest'
 'Kids and Family|Science Fiction and Fantasy'
 'Classics|Horror|Science Fiction and Fantasy'
 'Action and Adventure|Animation|Comedy|Kids and Family'
 'Drama|Special Interest'
 'Action and Adventure|Comedy|Drama|Mystery and Suspense'
 'Comedy|Kids and Family|Television'
 'Action and Adventure|Classics|Horror'
 'Action and Adventure|Classics|Western|Romance'
 'Action and Adventure|Art House and International|Drama|Kids and Family|Science Fiction and Fantasy'
 'Classics|Drama|Mystery and Suspense'
 'Action and Adventure|Art House and International|Science Fiction and Fantasy'
 'Art House and International|Comedy'
 'Mystery and Suspense|Science Fiction and Fantasy'
 'Classics|Drama|Musical and Performing Arts|Mystery and Suspense'
 'Action and Adventure|Classics|Drama|Western'
 'Action and Adventure|Horror|Science Fiction and Fantasy'
 'Comedy|Drama|Science Fiction and Fantasy|Romance'
 'Action and Adventure|Animation|Science Fiction and Fantasy'
 'Mystery and Suspense|Romance'
 'Documentary|Musical and Performing Arts|Special Interest'
 'Action and Adventure|Western|Romance'
 'Art House and International|Documentary|Drama|Special Interest'
 'Art House and International|Cult Movies|Drama'
 'Action and Adventure|Animation|Comedy|Science Fiction and Fantasy'
 'Animation|Comedy|Kids and Family'
 'Animation|Drama|Kids and Family|Science Fiction and Fantasy'
 'Art House and International|Classics|Drama|Horror|Science Fiction and Fantasy'
 'Classics|Drama|Romance'
 'Art House and International|Classics|Drama|Romance'
 'Documentary|Special Interest|Sports and Fitness'
 'Classics|Comedy|Drama|Kids and Family|Musical and Performing Arts'
 'Action and Adventure|Documentary|Television'
 'Action and Adventure|Drama|Mystery and Suspense|Television|Western'
 'Action and Adventure|Drama|Mystery and Suspense|Romance'
 'Classics|Comedy|Drama|Television'
 'Action and Adventure|Art House and International|Comedy|Drama'
 'Action and Adventure|Drama|Horror|Western'
 'Action and Adventure|Art House and International|Drama|Kids and Family|Mystery and Suspense'
 'Action and Adventure|Animation|Comedy'
 'Art House and International|Documentary|Special Interest'
 'Comedy|Drama|Science Fiction and Fantasy'
 'Animation|Anime and Manga|Art House and International|Horror|Science Fiction and Fantasy'
 'Art House and International|Comedy|Romance'
 'Action and Adventure|Comedy|Science Fiction and Fantasy'
 'Drama|Mystery and Suspense|Romance' 'Comedy|Special Interest'
 'Drama|Mystery and Suspense|Science Fiction and Fantasy'
 'Action and Adventure|Mystery and Suspense|Romance'
 'Classics|Musical and Performing Arts' 'Classics|Drama|Western'
 'Animation|Documentary|Drama' 'Special Interest'
 'Action and Adventure|Classics|Western' 'Kids and Family'
 'Animation|Kids and Family' 'Drama|Horror' 'Comedy|Mystery and Suspense'
 'Documentary|Drama|Special Interest' 'Animation|Special Interest'
 'Action and Adventure|Kids and Family|Science Fiction and Fantasy|Western'
 'Art House and International|Classics|Comedy|Drama|Musical and Performing Arts|Science Fiction and Fantasy|Romance'
 'Action and Adventure|Classics'
 'Action and Adventure|Art House and International|Comedy|Mystery and Suspense|Science Fiction and Fantasy'
 'Art House and International|Drama|Sports and Fitness' 'Western'
 'Comedy|Documentary|Musical and Performing Arts|Special Interest'
 'Art House and International|Horror|Mystery and Suspense'
 'Comedy|Cult Movies|Mystery and Suspense|Science Fiction and Fantasy'
 'Action and Adventure|Classics|Drama|Romance'
 'Action and Adventure|Art House and International|Mystery and Suspense|Special Interest'
 'Horror|Musical and Performing Arts|Science Fiction and Fantasy'
 'Art House and International|Classics|Comedy|Drama'
 'Action and Adventure|Animation|Comedy|Kids and Family|Science Fiction and Fantasy'
 'Comedy|Drama|Sports and Fitness'
 'Action and Adventure|Drama|Special Interest'
 'Action and Adventure|Animation|Kids and Family|Science Fiction and Fantasy'
 'Classics|Drama|Mystery and Suspense|Romance'
 'Action and Adventure|Comedy|Kids and Family|Science Fiction and Fantasy'
 'Comedy|Musical and Performing Arts|Science Fiction and Fantasy'
 'Art House and International|Comedy|Drama|Romance|Gay and Lesbian'
 'Science Fiction and Fantasy' 'Action and Adventure|Documentary'
 'Action and Adventure|Art House and International|Comedy|Cult Movies|Drama'
 'Action and Adventure|Drama|Romance'
 'Classics|Horror|Musical and Performing Arts|Science Fiction and Fantasy'
 'Classics|Drama|Musical and Performing Arts|Romance' 'Documentary|Drama'
 'Comedy|Documentary|Science Fiction and Fantasy|Special Interest'
 'Comedy|Cult Movies|Drama' 'Classics|Drama|Kids and Family|Romance'
 'Art House and International|Comedy|Kids and Family|Musical and Performing Arts|Romance'
 'Classics|Mystery and Suspense'
 'Art House and International|Classics|Drama'
 'Action and Adventure|Art House and International|Comedy|Drama|Mystery and Suspense'
 'Horror|Kids and Family|Mystery and Suspense|Science Fiction and Fantasy'
 'Action and Adventure|Horror|Mystery and Suspense'
 'Classics|Musical and Performing Arts|Romance'
 'Drama|Faith and Spirituality' 'Art House and International|Drama|Horror'
 'Action and Adventure|Drama|Mystery and Suspense|Science Fiction and Fantasy|Faith and Spirituality'
 'Action and Adventure|Art House and International|Drama|Mystery and Suspense|Romance'
 'Classics|Comedy|Mystery and Suspense'
 'Action and Adventure|Kids and Family'
 'Action and Adventure|Art House and International|Classics|Drama|Romance'
 'Comedy|Musical and Performing Arts|Television'
 'Art House and International|Documentary' 'Comedy|Documentary'
 'Action and Adventure|Animation|Comedy|Drama|Kids and Family|Musical and Performing Arts'
 'Action and Adventure|Animation|Classics|Comedy|Kids and Family|Musical and Performing Arts'
 'Animation|Kids and Family|Science Fiction and Fantasy'
 'Art House and International|Comedy|Mystery and Suspense'
 'Drama|Science Fiction and Fantasy|Western'
 'Mystery and Suspense|Science Fiction and Fantasy|Western'
 'Comedy|Drama|Special Interest'
 'Art House and International|Comedy|Drama|Science Fiction and Fantasy|Special Interest'
 'Action and Adventure|Comedy|Western'
 'Animation|Art House and International|Comedy|Special Interest'
 'Documentary|Sports and Fitness'
 'Documentary|Special Interest|Television'
 'Action and Adventure|Drama|Horror|Science Fiction and Fantasy'
 'Art House and International|Documentary|Drama|Musical and Performing Arts|Special Interest'
 'Action and Adventure|Art House and International|Mystery and Suspense'
 'Action and Adventure|Comedy|Kids and Family|Mystery and Suspense'
 'Art House and International|Comedy|Drama|Science Fiction and Fantasy'
 'Art House and International|Documentary|Drama'
 'Action and Adventure|Comedy|Drama|Kids and Family'
 'Action and Adventure|Classics|Drama|Horror|Mystery and Suspense|Science Fiction and Fantasy'
 'Art House and International|Comedy|Horror'
 'Art House and International|Comedy|Drama|Gay and Lesbian'
 'Drama|Kids and Family|Faith and Spirituality'
 'Action and Adventure|Comedy|Musical and Performing Arts|Science Fiction and Fantasy|Western'
 'Action and Adventure|Classics|Comedy|Musical and Performing Arts'
 'Art House and International|Classics|Comedy|Drama|Romance'
 'Action and Adventure|Animation|Comedy|Drama|Kids and Family'
 'Classics|Comedy|Kids and Family|Romance'
 'Action and Adventure|Comedy|Kids and Family|Mystery and Suspense|Science Fiction and Fantasy'
 'Action and Adventure|Horror|Kids and Family|Science Fiction and Fantasy'
 'Classics|Horror|Mystery and Suspense'
 'Comedy|Horror|Mystery and Suspense'
 'Classics|Drama|Science Fiction and Fantasy'
 'Action and Adventure|Classics|Drama|Mystery and Suspense|Romance'
 'Art House and International|Drama|Mystery and Suspense|Romance'
 'Documentary|Special Interest|Faith and Spirituality'
 'Animation|Science Fiction and Fantasy'
 'Action and Adventure|Drama|Mystery and Suspense|Science Fiction and Fantasy'
 'Comedy|Television'
 'Action and Adventure|Classics|Science Fiction and Fantasy'
 'Kids and Family|Musical and Performing Arts'
 'Classics|Comedy|Musical and Performing Arts|Western'
 'Art House and International|Drama|Horror|Mystery and Suspense'
 'Action and Adventure|Comedy|Horror|Romance'
 'Action and Adventure|Animation|Kids and Family'
 'Drama|Musical and Performing Arts|Faith and Spirituality'
 'Animation|Art House and International|Kids and Family'
 'Drama|Mystery and Suspense|Television'
 'Action and Adventure|Anime and Manga|Art House and International|Science Fiction and Fantasy'
 'Art House and International|Documentary|Faith and Spirituality'
 'Classics|Science Fiction and Fantasy'
 'Art House and International|Comedy|Horror|Mystery and Suspense'
 'Drama|Special Interest|Sports and Fitness'
 'Comedy|Mystery and Suspense|Romance'
 'Comedy|Horror|Science Fiction and Fantasy' 'Classics|Comedy|Western'
 'Action and Adventure|Comedy|Kids and Family|Science Fiction and Fantasy|Romance'
 'Comedy|Drama|Horror|Mystery and Suspense'
 'Horror|Science Fiction and Fantasy|Television|Romance'
 'Action and Adventure|Drama|Mystery and Suspense|Special Interest'

## Handling missing values column by column

### Filling in categorical columns with 'unknown'

In [516]:

for col in ['synopsis', 'rating', 'genre', 'director', 'writer', 'studio']:
    if col in rt_movie_info_clean.columns:
            initial_missing_count = rt_movie_info_clean[col].isnull().sum()
            if initial_missing_count > 0:
                rt_movie_info_clean[col] = rt_movie_info_clean[col].fillna('Unknown')
                print(f"Filled {initial_missing_count} missing '{col}' values with 'Unknown'.")

Filled 62 missing 'synopsis' values with 'Unknown'.
Filled 3 missing 'rating' values with 'Unknown'.
Filled 8 missing 'genre' values with 'Unknown'.
Filled 199 missing 'director' values with 'Unknown'.
Filled 449 missing 'writer' values with 'Unknown'.
Filled 1066 missing 'studio' values with 'Unknown'.

In [517]:
rt_movie_info_clean.isna().sum()

id                 0
synopsis           0
rating             0
genre              0
director           0
writer             0
theater_date     359
dvd_date         359
currency        1220
box_office      1220
runtime           30
studio             0
dtype: int64

In [518]:
# converting theatre date and dvd date into datetime format
rt_movie_info_clean['theater_date'] = pd.to_datetime(rt_movie_info_clean['theater_date'], errors='coerce')
rt_movie_info_clean['dvd_date'] = pd.to_datetime(rt_movie_info_clean['dvd_date'], errors='coerce')

In [519]:
# filling in missing runtime values with median runtime
rt_movie_info_clean["runtime"]= rt_movie_info_clean["runtime"].astype(str).str.replace('minutes', '', regex= False)
rt_movie_info_clean["runtime"]= pd.to_numeric(rt_movie_info_clean["runtime"], errors= 'coerce')
# filling missing values with median values
runtime_median= rt_movie_info_clean["runtime"].median()                                     
rt_movie_info_clean["runtime"]= rt_movie_info_clean["runtime"].fillna(runtime_median)

In [520]:
rt_movie_info_clean.isna().sum()

id                 0
synopsis           0
rating             0
genre              0
director           0
writer             0
theater_date     359
dvd_date         359
currency        1220
box_office      1220
runtime            0
studio             0
dtype: int64

In [521]:
# dropping missing theater date and dvd date missing values
rt_movie_info_clean = rt_movie_info_clean.drop(columns=['currency', 'box_office'])

## Cleaning tmdb_movies_df(The movie DB dataset)

In [522]:
tmdb_movies_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26517 entries, 0 to 26516
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         26517 non-null  int64
 1   genre_ids          26517 non-null  object
 2   id                 26517 non-null  int64
 3   original_language  26517 non-null  object
 4   original_title     26517 non-null  object
 5   popularity         26517 non-null  float64
 6   release_date       26517 non-null  object
 7   title              26517 non-null  object
 8   vote_average       26517 non-null  float64
 9   vote_count         26517 non-null  int64
dtypes: float64(2), int64(3), object(5)
memory usage: 2.0+ MB

In [523]:
# dropping unnamed column
tmdb_movies_df.drop(columns=["Unnamed: 0", 'genre_ids'], inplace=True)

In [524]:
# checking for unique values in each column
for column in tmdb_movies_df.columns:
    print(f"\n{column} unique values:")
    print(tmdb_movies_df[column].unique())

id unique values:
[ 12444  10191  10138 ... 381231 366854 309885]

original_language unique values:
['en' 'nl' 'es' 'ja' 'sv' 'de' 'fr' 'cn' 'it' 'ru' 'zh' 'hi' 'no' 'ko'
 'da' 'fi' 'pl' 'te' 'hu' 'tr' 'pt' 'he' 'fa' 'th' 'cs' 'et' 'tl' 'lt'
 'xx' 'bs' 'ar' 'is' 'el' 'mr' 'hr' 'ro' 'sr' 'uk' 'nb' 'hz' 'ca' 'bg'
 'sl' 'lv' 'si' 'ab' 'ta' 'bo' 'id' 'sq' 'bn' 'gu' 'lo' 'ne' 'kk' 'hy'
 'ps' 'kn' 'vi' 'ku' 'ka' 'ml' 'ur' 'mi' 'eu' 'sn' 'cy' 'ha' 'ky' 'yi'
 'pa' 'xh' 'cr' 'sw' 'af' 'dz']

original_title unique values:
['Harry Potter and the Deathly Hallows: Part 1' 'How to Train Your Dragon'
 'Iron Man 2' ... 'The Last One' 'Trailer Made' 'The Church']

popularity unique values:
[33.533 28.734 28.515 ...  0.612  0.609  0.607]

release_date unique values:
['2010-11-19' '2010-03-26' '2010-05-07' ... '2018-05-08' '2018-08-02'
 '2018-05-26']

title unique values:
['Harry Potter and the Deathly Hallows: Part 1' 'How to Train Your Dragon'
 'Iron Man 2' ... 'The Last One' 'Trailer Made' 'The Church']

vote_average unique values:
[ 7.7  6.8  7.9  8.3  6.1  7.4  7.2  7.5  6.6  6.   6.7  4.5  7.3  8.1
  6.3  4.6  5.7  5.9  8.2  6.2  6.4  7.6  6.5  7.1  5.6  5.3  7.   5.8
  4.9  5.1  5.5  6.9  5.4  7.8  4.7  4.1  4.8  3.2  8.   3.7  5.2  2.7
  4.4  5.   2.9  2.   4.   4.2  3.9  4.3  3.5  3.8  3.6  3.4  3.3  3.1
  3.   2.5  2.6 10.   2.2  1.7  2.8  2.3  1.6  1.8  2.4  1.5  8.6  1.9
  9.   8.7  0.5  1.   8.4  2.1  8.8  1.3  9.5  8.5  9.8  0.   8.9  9.3
  9.4  9.2  0.8  1.2  1.4  9.1  9.7]

vote_count unique values:
[10788  7610 12368 ...  1163   285   721]

In [525]:
# standardizing categorical columns for consistency (lowercase and strip)
tmdb_movies_df['original_language']= tmdb_movies_df['original_language'].str.strip().str.lower()
tmdb_movies_df['original_title']= tmdb_movies_df['original_title'].str.strip()
tmdb_movies_df['title']= tmdb_movies_df['title'].str.strip()

In [526]:
# converting release date to datetime format
tmdb_movies_df["release_date"] = pd.to_datetime(tmdb_movies_df["release_date"], errors='coerce')

In [527]:
# extract year and month from movie_budgets tmdb df
# tmdb_movies_df['release_year'] = tmdb_movies_df['release_date'].dt.year
# tmdb_movies_df['release_month'] = tmdb_movies_df['release_date'].dt.month

In [528]:
tmdb_movies_df.columns

Index(['id', 'original_language', 'original_title', 'popularity',
       'release_date', 'title', 'vote_average', 'vote_count'],
      dtype='object')

## Cleaning movie_budgets df(The Numbers Dataset)

In [529]:
tn_movie_budgets_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5782 entries, 0 to 5781
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 5782 non-null   int64
 1   release_date       5782 non-null   object
 2   movie              5782 non-null   object
 3   production_budget  5782 non-null   object
 4   domestic_gross     5782 non-null   object
 5   worldwide_gross    5782 non-null   object
dtypes: int64(1), object(5)
memory usage: 271.2+ KB

In [530]:
# checking for unique values in each column
for column in tn_movie_budgets_df.columns:
    print(f"\n{column} unique values:")
    print(tn_movie_budgets_df[column].unique())

id unique values:
[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]

release_date unique values:
['Dec 18, 2009' 'May 20, 2011' 'Jun 7, 2019' ... 'Aug 14, 2008'
 'Feb 26, 1993' 'Jul 13, 2005']

movie unique values:
['Avatar' 'Pirates of the Caribbean: On Stranger Tides' 'Dark Phoenix' ...
 'Return to the Land of Wonders' 'A Plague So Pleasant'
 'My Date With Drew']

production_budget unique values:
['$425,000,000' '$410,600,000' '$350,000,000' '$330,600,000'
 '$317,000,000' '$306,000,000' '$300,000,000' '$275,000,000'
 '$260,000,000' '$258,000,000' '$250,000,000' '$232,000,000'
 '$230,000,000' '$225,000,000' '$220,000,000' '$217,000,000'
 '$215,000,000' '$210,000,000' '$207,000,000' '$205,000,000'
 '$200,000,000' '$195,000,000' '$190,000,000' '$187,500,000'
 '$186,000,000' '$185,000,000' '$182,000,000' '$180,000,000'
 '$179,000,000' '$178,000,000' '$175,000,000' '$170,000,000'
 '$165,000,000' '$163,000,000' '$160,000,000' '$156,000,000'
 '$155,000,000' '$152,000,000' '$151,500,000' '$151,000,000'
 '$150,000,000' '$149,000,000' '$145,000,000' '$144,000,000'
 '$142,000,000' '$140,000,000' '$139,000,000' '$138,000,000'
 '$137,500,000' '$137,000,000' '$136,200,000' '$135,000,000'
 '$132,900,000' '$132,000,000' '$130,000,000' '$129,000,000'
 '$127,500,000' '$127,000,000' '$125,000,000' '$123,000,000'
 '$120,000,000' '$117,000,000' '$116,000,000' '$115,000,000'
 '$113,500,000' '$112,000,000' '$111,000,000' '$110,000,000'
 '$109,000,000' '$108,000,000' '$106,000,000' '$105,000,000'
 '$104,000,000' '$103,300,000' '$103,000,000' '$102,500,000'
 '$102,000,000' '$100,000,000' '$99,000,000' '$98,000,000' '$97,000,000'
 '$95,000,000' '$94,000,000' '$93,000,000' '$92,500,000' '$92,000,000'
 '$91,000,000' '$90,000,000' '$88,000,000' '$87,500,000' '$87,000,000'
 '$86,000,000' '$85,000,000' '$84,000,000' '$82,500,000' '$82,000,000'
 '$81,000,000' '$80,000,000' '$79,300,000' '$79,000,000' '$78,000,000'
 '$77,600,000' '$77,500,000' '$77,000,000' '$76,000,000' '$75,000,000'
 '$74,000,000' '$73,243,106' '$73,000,000' '$72,500,000' '$72,000,000'
 '$71,682,975' '$71,500,000' '$70,702,619' '$70,000,000' '$69,000,000'
 '$68,000,000' '$67,500,000' '$67,000,000' '$66,000,000' '$65,000,000'
 '$64,000,000' '$63,700,000' '$63,000,000' '$62,000,000' '$61,000,000'
 '$60,720,000' '$60,000,000' '$59,500,000' '$59,000,000' '$58,000,000'
 '$57,500,000' '$57,000,000' '$56,200,000' '$56,000,000' '$55,000,000'
 '$54,000,000' '$53,012,938' '$53,000,000' '$52,500,000' '$52,000,000'
 '$51,000,000' '$50,200,000' '$50,000,000' '$49,800,000' '$49,000,000'
 '$48,000,000' '$47,500,000' '$47,000,000' '$46,500,000' '$46,000,000'
 '$45,500,000' '$45,000,000' '$44,500,000' '$44,000,000' '$43,000,000'
 '$42,500,000' '$42,000,000' '$41,000,000' '$40,000,000' '$39,000,000'
 '$38,600,000' '$38,000,000' '$37,500,000' '$37,000,000' '$36,500,000'
 '$36,000,000' '$35,200,000' '$35,000,000' '$34,800,000' '$34,000,000'
 '$33,500,000' '$33,000,000' '$32,500,000' '$32,000,000' '$31,500,000'
 '$31,000,000' '$30,250,000' '$30,000,000' '$29,200,000' '$29,000,000'
 '$28,700,000' '$28,500,000' '$28,000,000' '$27,500,000' '$27,000,000'
 '$26,700,000' '$26,000,000' '$25,530,000' '$25,500,000' '$25,100,000'
 '$25,000,000' '$24,200,000' '$24,000,000' '$23,600,000' '$23,000,000'
 '$22,700,000' '$22,500,000' '$22,000,000' '$21,600,000' '$21,500,000'
 '$21,000,000' '$20,700,000' '$20,500,000' '$20,000,000' '$19,800,000'
 '$19,700,000' '$19,500,000' '$19,400,000' '$19,200,000' '$19,100,000'
 '$19,000,000' '$18,975,000' '$18,900,000' '$18,500,000' '$18,000,000'
 '$17,900,000' '$17,700,000' '$17,500,000' '$17,000,000' '$16,800,000'
 '$16,500,000' '$16,400,000' '$16,000,000' '$15,700,000' '$15,600,000'
 '$15,500,000' '$15,300,000' '$15,250,000' '$15,000,000' '$14,600,000'
 '$14,500,000' '$14,400,000' '$14,200,000' '$14,000,000' '$13,900,000'
 '$13,700,000' '$13,500,000' '$13,400,000' '$13,300,000' '$13,200,000'
 '$13,000,000' '$12,800,000' '$12,700,000' '$12,600,000' '$12,500,000'
 '$12,300,000' '$12,000,000' '$11,900,000' '$11,800,000' '$11,500,000'
 '$11,400,000' '$11,000,000' '$10,800,000' '$10,750,000' '$10,700,000'
 '$10,600,000' '$10,500,000' '$10,400,000' '$10,350,000' '$10,300,000'
 '$10,100,000' '$10,000,000' '$9,900,000' '$9,800,000' '$9,700,000'
 '$9,600,000' '$9,500,000' '$9,400,000' '$9,300,000' '$9,200,000'
 '$9,100,000' '$9,000,000' '$8,900,000' '$8,800,000' '$8,600,000'
 '$8,500,000' '$8,470,000' '$8,400,000' '$8,300,000' '$8,250,000'
 '$8,200,000' '$8,000,000' '$7,900,000' '$7,800,000' '$7,700,000'
 '$7,500,000' '$7,400,000' '$7,303,082' '$7,300,000' '$7,250,000'
 '$7,200,000' '$7,000,000' '$6,900,000' '$6,840,000' '$6,800,000'
 '$6,750,000' '$6,700,000' '$6,600,000' '$6,537,890' '$6,500,000'
 '$6,400,000' '$6,250,000' '$6,200,000' '$6,100,000' '$6,000,000'
 '$5,952,000' '$5,900,000' '$5,800,000' '$5,700,000' '$5,600,000'
 '$5,500,000' '$5,400,000' '$5,300,000' '$5,250,000' '$5,200,000'
 '$5,100,000' '$5,000,000' '$4,900,000' '$4,833,610' '$4,800,000'
 '$4,750,000' '$4,700,000' '$4,638,783' '$4,600,000' '$4,500,000'
 '$4,400,000' '$4,357,373' '$4,300,000' '$4,200,000' '$4,030,000'
 '$4,000,000' '$3,900,000' '$3,800,000' '$3,768,785' '$3,750,000'
 '$3,716,946' '$3,700,000' '$3,600,000' '$3,500,000' '$3,450,000'
 '$3,440,000' '$3,400,000' '$3,380,000' '$3,300,000' '$3,250,000'
 '$3,200,000' '$3,180,000' '$3,100,000' '$3,000,000' '$2,931,000'
 '$2,900,000' '$2,883,848' '$2,850,000' '$2,800,000' '$2,777,000'
 '$2,750,000' '$2,700,000' '$2,686,000' '$2,660,000' '$2,650,000'
 '$2,627,000' '$2,600,000' '$2,540,000' '$2,500,000' '$2,450,000'
 '$2,400,000' '$2,380,000' '$2,361,000' '$2,300,000' '$2,289,247'
 '$2,280,000' '$2,250,000' '$2,200,000' '$2,160,000' '$2,150,000'
 '$2,100,000' '$2,000,000' '$1,987,650' '$1,950,000' '$1,900,000'
 '$1,800,000' '$1,750,000' '$1,700,000' '$1,660,000' '$1,650,000'
 '$1,644,000' '$1,600,000' '$1,577,000' '$1,500,000' '$1,488,000'
 '$1,455,000' '$1,400,000' '$1,377,800' '$1,350,000' '$1,305,000'
 '$1,300,000' '$1,288,000' '$1,250,000' '$1,200,000' '$1,150,000'
 '$1,125,000' '$1,100,000' '$1,070,000' '$1,039,000' '$1,000,000'
 '$989,000' '$950,000' '$930,000' '$916,000' '$913,000' '$910,000'
 '$900,000' '$858,000' '$850,000' '$840,000' '$825,000' '$820,000'
 '$800,000' '$780,000' '$777,000' '$775,000' '$750,000' '$747,000'
 '$730,000' '$700,000' '$672,000' '$658,000' '$650,000' '$640,000'
 '$625,000' '$609,000' '$600,000' '$560,000' '$558,000' '$550,000'
 '$546,173' '$500,000' '$475,000' '$450,000' '$439,000' '$430,000'
 '$425,000' '$420,000' '$400,000' '$385,907' '$379,000' '$375,000'
 '$350,000' '$340,000' '$325,000' '$323,000' '$312,000' '$300,000'
 '$290,000' '$270,000' '$250,000' '$245,000' '$240,000' '$230,000'
 '$225,000' '$210,000' '$200,000' '$190,000' '$180,000' '$175,000'
 '$170,000' '$168,000' '$160,000' '$150,000' '$140,000' '$135,000'
 '$134,000' '$125,000' '$120,000' '$114,000' '$110,000' '$103,000'
 '$100,000' '$87,000' '$79,000' '$75,000' '$70,000' '$68,000' '$66,000'
 '$65,000' '$60,000' '$55,000' '$50,000' '$45,000' '$42,000' '$40,000'
 '$35,000' '$30,000' '$27,000' '$25,000' '$23,000' '$22,000' '$20,000'
 '$17,300' '$15,000' '$12,000' '$10,000' '$9,000' '$7,000' '$6,000'
 '$5,000' '$1,400' '$1,100']

domestic_gross unique values:
['$760,507,625' '$241,063,875' '$42,762,350' ... '$48,482' '$1,338'
 '$181,041']

worldwide_gross unique values:
['$2,776,345,279' '$1,045,663,875' '$149,762,350' ... '$240,495' '$1,338'
 '$181,041']

In [531]:
# converting currency strings to numeric 
print("\ntn_movie_budgets_df...")
for col in ['production_budget', 'domestic_gross', 'worldwide_gross']:
        if col in tn_movie_budgets_df.columns and tn_movie_budgets_df[col].dtype == 'object':
            tn_movie_budgets_df[col] = tn_movie_budgets_df[col].astype(str).str.replace('$', '', regex=False).str.replace(',', '', regex=False)
            tn_movie_budgets_df[col] = pd.to_numeric(tn_movie_budgets_df[col], errors='coerce')

tn_movie_budgets_df...

In [532]:
# checking 
tn_movie_budgets_df.head(10)

,id,release_date,movie,production_budget,domestic_gross,worldwide_gross
0,1,"Dec 18, 2009",Avatar,425000000,760507625,2776345279
1,2,"May 20, 2011",Pirates of the Caribbean: On Stranger Tides,410600000,241063875,1045663875
2,3,"Jun 7, 2019",Dark Phoenix,350000000,42762350,149762350
3,4,"May 1, 2015",Avengers: Age of Ultron,330600000,459005868,1403013963
4,5,"Dec 15, 2017",Star Wars Ep. VIII: The Last Jedi,317000000,620181382,1316721747
5,6,"Dec 18, 2015",Star Wars Ep. VII: The Force Awakens,306000000,936662225,2053311220
6,7,"Apr 27, 2018",Avengers: Infinity War,300000000,678815482,2048134200
7,8,"May 24, 2007",Pirates of the Caribbean: At Worldâs End,300000000,309420425,963420425
8,9,"Nov 17, 2017",Justice League,300000000,229024295,655945209
9,10,"Nov 6, 2015",Spectre,300000000,200074175,879620923

In [533]:
# converting release date to datetime format
tn_movie_budgets_df['release_date']= pd.to_datetime(tn_movie_budgets_df['release_date'])

In [534]:
# Extract release year and month from tn budget
tn_movie_budgets_df['release_year'] = tn_movie_budgets_df['release_date'].dt.year
tn_movie_budgets_df['release_month'] = tn_movie_budgets_df['release_date'].dt.month

In [535]:
tn_movie_budgets_df.columns

Index(['id', 'release_date', 'movie', 'production_budget', 'domestic_gross',
       'worldwide_gross', 'release_year', 'release_month'],
      dtype='object')

## Feature engineering

### Calculating review counts from rt_reviews_clean_df

In [536]:
# computing review counts and freshness score
review_counts= rt_reviews_clean_df.groupby('id').agg(
    Review_counts= ('fresh', 'count'),
    Freshness_score= ('fresh', lambda x: (x== 'fresh').sum()/ len(x))).reset_index()
review_counts

        id  Review_counts  Freshness_score
0        3            163         0.631902
1        5             23         0.782609
2        6             57         0.561404
3        8             75         0.746667
4       10            108         0.462963
...    ...            ...              ...
1130  1996            143         0.671329
1131  1997             28         0.357143
1132  1998              2         1.000000
1133  1999             46         0.586957
1134  2000             38         0.473684

[1135 rows x 3 columns]

### Merging review_counts and rt_movie_info_clean df

In [537]:
rt_combined_df= pd.merge(rt_movie_info_clean, review_counts, on= 'id', how= 'left')
rt_combined_df

,id,synopsis,rating,genre,director,writer,theater_date,dvd_date,runtime,studio,Review_counts,Freshness_score
0,1,"This gritty, fast-paced, and innovative police...",R,Action and Adventure|Classics|Drama,William Friedkin,Ernest Tidyman,1971-10-09,2001-09-25,104.0,Unknown,NaN,NaN
1,3,"New York City, not-too-distant-future: Eric Pa...",R,Drama|Science Fiction and Fantasy,David Cronenberg,David Cronenberg|Don DeLillo,2012-08-17,2013-01-01,108.0,Entertainment One,163.0,0.631902
2,5,Illeana Douglas delivers a superb performance ...,R,Drama|Musical and Performing Arts,Allison Anders,Allison Anders,1996-09-13,2000-04-18,116.0,Unknown,23.0,0.782609
3,6,Michael Douglas runs afoul of a treacherous su...,R,Drama|Mystery and Suspense,Barry Levinson,Paul Attanasio|Michael Crichton,1994-12-09,1997-08-27,128.0,Unknown,57.0,0.561404
4,7,Unknown,NR,Drama|Romance,Rodney Bennett,Giles Cooper,NaT,NaT,200.0,Unknown,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
1555,1996,Forget terrorists or hijackers -- there's a ha...,R,Action and Adventure|Horror|Mystery and Suspense,Unknown,Unknown,2006-08-18,2007-01-02,106.0,New Line Cinema,143.0,0.671329
1556,1997,The popular Saturday Night Live sketch was exp...,PG,Comedy|Science Fiction and Fantasy,Steve Barron,Terry Turner|Tom Davis|Dan Aykroyd|Bonnie Turner,1993-07-23,2001-04-17,88.0,Paramount Vantage,28.0,0.357143
1557,1998,"Based on a novel by Richard Powell, when the l...",G,Classics|Comedy|Drama|Musical and Performing Arts,Gordon Douglas,Unknown,1962-01-01,2004-05-11,111.0,Unknown,2.0,1.000000
1558,1999,The Sandlot is a coming-of-age story about a g...,PG,Comedy|Drama|Kids and Family|Sports and Fitness,David Mickey Evans,David Mickey Evans|Robert Gunter,1993-04-01,2002-01-29,101.0,Unknown,46.0,0.586957
1559,2000,"Suspended from the force, Paris cop Hubert is ...",R,Action and Adventure|Art House and Internation...,Unknown,Luc Besson,2001-09-27,2003-02-11,94.0,Columbia Pictures,38.0,0.473684

### Merging tmdb_movies_df and tn_movie_budgets_df

In [538]:
# renaming tmdb title column to tmdb_title for differentiation
tmdb_movies_df.rename(columns= {'title': 'tmdb_title'}, inplace= True)

In [539]:
# renaming movie column in tn_movie_budgets_df for easy understanding when merging with tmdb
tn_movie_budgets_df.rename(columns={ 'movie': 'title'}, inplace= True)

In [543]:
# merging tn_movie_budgets_df and tmdb_movies_df on title and release year
tmdb_tn_merged= pd.merge(tn_movie_budgets_df, tmdb_movies_df, left_on= ['title', 'release_year'], right_on=['tmdb_title', 'release_year'], how= 'left')
tmdb_tn_merged

,id_x,release_date_x,title,production_budget,domestic_gross,worldwide_gross,release_year,release_month_x,id_y,original_language,original_title,popularity,release_date_y,tmdb_title,vote_average,vote_count,release_month_y
0,1,2009-12-18,Avatar,425000000,760507625,2776345279,2009,12,19995.0,en,Avatar,26.526,2009-12-18,Avatar,7.4,18676.0,12.0
1,2,2011-05-20,Pirates of the Caribbean: On Stranger Tides,410600000,241063875,1045663875,2011,5,1865.0,en,Pirates of the Caribbean: On Stranger Tides,30.579,2011-05-20,Pirates of the Caribbean: On Stranger Tides,6.4,8571.0,5.0
2,3,2019-06-07,Dark Phoenix,350000000,42762350,149762350,2019,6,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN
3,4,2015-05-01,Avengers: Age of Ultron,330600000,459005868,1403013963,2015,5,99861.0,en,Avengers: Age of Ultron,44.383,2015-05-01,Avengers: Age of Ultron,7.3,13457.0,5.0
4,5,2017-12-15,Star Wars Ep. VIII: The Last Jedi,317000000,620181382,1316721747,2017,12,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5935,78,2018-12-31,Red 11,7000,0,0,2018,12,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN
5936,79,1999-04-02,Following,6000,48482,240495,1999,4,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN
5937,80,2005-07-13,Return to the Land of Wonders,5000,1338,1338,2005,7,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN
5938,81,2015-09-29,A Plague So Pleasant,1400,0,0,2015,9,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN
5939,82,2005-08-05,My Date With Drew,1100,181041,181041,2005,8,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN

In [544]:
# Rename id_x for merging
tmdb_tn_merged.rename(columns={'id_x': 'id'}, inplace=True)

In [547]:
merged_2= pd.merge(tmdb_tn_merged, rt_combined_df[['id', 'genre', 'rating', 'Review_counts', 'Freshness_score']], on='id', how='left')
merged_2

,id,release_date_x,title,production_budget,domestic_gross,worldwide_gross,release_year,release_month_x,id_y,original_language,...,popularity,release_date_y,tmdb_title,vote_average,vote_count,release_month_y,genre,rating,Review_counts,Freshness_score
0,1,2009-12-18,Avatar,425000000,760507625,2776345279,2009,12,19995.0,en,...,26.526,2009-12-18,Avatar,7.4,18676.0,12.0,Action and Adventure|Classics|Drama,R,NaN,NaN
1,2,2011-05-20,Pirates of the Caribbean: On Stranger Tides,410600000,241063875,1045663875,2011,5,1865.0,en,...,30.579,2011-05-20,Pirates of the Caribbean: On Stranger Tides,6.4,8571.0,5.0,NaN,NaN,NaN,NaN
2,3,2019-06-07,Dark Phoenix,350000000,42762350,149762350,2019,6,NaN,NaN,...,NaN,NaT,NaN,NaN,NaN,NaN,Drama|Science Fiction and Fantasy,R,163.0,0.631902
3,4,2015-05-01,Avengers: Age of Ultron,330600000,459005868,1403013963,2015,5,99861.0,en,...,44.383,2015-05-01,Avengers: Age of Ultron,7.3,13457.0,5.0,NaN,NaN,NaN,NaN
4,5,2017-12-15,Star Wars Ep. VIII: The Last Jedi,317000000,620181382,1316721747,2017,12,NaN,NaN,...,NaN,NaT,NaN,NaN,NaN,NaN,Drama|Musical and Performing Arts,R,23.0,0.782609
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5935,78,2018-12-31,Red 11,7000,0,0,2018,12,NaN,NaN,...,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5936,79,1999-04-02,Following,6000,48482,240495,1999,4,NaN,NaN,...,NaN,NaT,NaN,NaN,NaN,NaN,Action and Adventure|Drama|Mystery and Suspense,R,18.0,0.611111
5937,80,2005-07-13,Return to the Land of Wonders,5000,1338,1338,2005,7,NaN,NaN,...,NaN,NaT,NaN,NaN,NaN,NaN,Action and Adventure|Art House and Internation...,NR,15.0,0.866667
5938,81,2015-09-29,A Plague So Pleasant,1400,0,0,2015,9,NaN,NaN,...,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5939,82,2005-08-05,My Date With Drew,1100,181041,181041,2005,8,NaN,NaN,...,NaN,NaT,NaN,NaN,NaN,NaN,Comedy|Mystery and Suspense|Science Fiction an...,R,102.0,0.852941

### Final feature engineering

In [550]:
merged_2['Profit']= merged_2['worldwide_gross']- merged_2['production_budget']
merged_2['ROI'] = merged_2['Profit'] / merged_2['production_budget']
merged_2['Domestic_vs_Worldwide_Ratio'] = merged_2['domestic_gross'] / merged_2['worldwide_gross']
merged_2['Release_Month'] = merged_2['release_date_x'].dt.month
merged_2['Day_of_Week'] = merged_2['release_date_x'].dt.day_name()

In [551]:
merged_2.head(10)

,id,release_date_x,title,production_budget,domestic_gross,worldwide_gross,release_year,release_month_x,id_y,original_language,...,genre,rating,Review_counts,Freshness_score,profit,Profit,ROI,Domestic_vs_Worldwide_Ratio,Release_Month,Day_of_Week
0,1,2009-12-18,Avatar,425000000,760507625,2776345279,2009,12,19995.0,en,...,Action and Adventure|Classics|Drama,R,NaN,NaN,2351345279,2351345279,5.532577,0.273924,12,Friday
1,2,2011-05-20,Pirates of the Caribbean: On Stranger Tides,410600000,241063875,1045663875,2011,5,1865.0,en,...,NaN,NaN,NaN,NaN,635063875,635063875,1.546673,0.230537,5,Friday
2,3,2019-06-07,Dark Phoenix,350000000,42762350,149762350,2019,6,NaN,NaN,...,Drama|Science Fiction and Fantasy,R,163.0,0.631902,-200237650,-200237650,-0.572108,0.285535,6,Friday
3,4,2015-05-01,Avengers: Age of Ultron,330600000,459005868,1403013963,2015,5,99861.0,en,...,NaN,NaN,NaN,NaN,1072413963,1072413963,3.243841,0.327157,5,Friday
4,5,2017-12-15,Star Wars Ep. VIII: The Last Jedi,317000000,620181382,1316721747,2017,12,NaN,NaN,...,Drama|Musical and Performing Arts,R,23.0,0.782609,999721747,999721747,3.153696,0.471004,12,Friday
5,6,2015-12-18,Star Wars Ep. VII: The Force Awakens,306000000,936662225,2053311220,2015,12,NaN,NaN,...,Drama|Mystery and Suspense,R,57.0,0.561404,1747311220,1747311220,5.710167,0.456172,12,Friday
6,7,2018-04-27,Avengers: Infinity War,300000000,678815482,2048134200,2018,4,299536.0,en,...,Drama|Romance,NR,NaN,NaN,1748134200,1748134200,5.827114,0.331431,4,Friday
7,8,2007-05-24,Pirates of the Caribbean: At Worldâs End,300000000,309420425,963420425,2007,5,NaN,NaN,...,Drama|Kids and Family,PG,75.0,0.746667,663420425,663420425,2.211401,0.321169,5,Thursday
8,9,2017-11-17,Justice League,300000000,229024295,655945209,2017,11,141052.0,en,...,NaN,NaN,NaN,NaN,355945209,355945209,1.186484,0.349152,11,Friday
9,9,2017-11-17,Justice League,300000000,229024295,655945209,2017,11,141052.0,en,...,NaN,NaN,NaN,NaN,355945209,355945209,1.186484,0.349152,11,Friday

In [552]:
merged_2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5940 entries, 0 to 5939
Data columns (total 27 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   id                           5940 non-null   int64
 1   release_date_x               5940 non-null   datetime64[ns]
 2   title                        5940 non-null   object
 3   production_budget            5940 non-null   int64
 4   domestic_gross               5940 non-null   int64
 5   worldwide_gross              5940 non-null   int64
 6   release_year                 5940 non-null   int64
 7   release_month_x              5940 non-null   int64
 8   id_y                         1758 non-null   float64
 9   original_language            1758 non-null   object
 10  original_title               1758 non-null   object
 11  popularity                   1758 non-null   float64
 12  release_date_y               1758 non-null   datetime64[ns]
 13  tmdb_title                   1758 non-null   object
 14  vote_average                 1758 non-null   float64
 15  vote_count                   1758 non-null   float64
 16  release_month_y              1758 non-null   float64
 17  genre                        4809 non-null   object
 18  rating                       4809 non-null   object
 19  Review_counts                3509 non-null   float64
 20  Freshness_score              3509 non-null   float64
 21  profit                       5940 non-null   int64
 22  Profit                       5940 non-null   int64
 23  ROI                          5940 non-null   float64
 24  Domestic_vs_Worldwide_Ratio  5570 non-null   float64
 25  Release_Month                5940 non-null   int64
 26  Day_of_Week                  5940 non-null   object
dtypes: datetime64[ns](2), float64(9), int64(9), object(7)
memory usage: 1.4+ MB

In [557]:
# Drop suffix columns and low-value metadata
redundant_cols = [col for col in merged_2.columns if col.endswith('_x') or col.endswith('_y')]
low_value_cols = [
    'id_y', 'tmdb_title', 'original_title', 'original_language', 'currency',
    'dvd_date', 'release_date_y', 'release_date_x', 'rating', 'writer',
    'synopsis', 'theater_date', 'popularity', 'vote_count', 'vote_average','Unnamed: 0','genre_ids'
]
drop_columns = list(set(redundant_cols + low_value_cols))
merged_2.drop(columns=drop_columns, errors='ignore', inplace=True)
merged_2.tail()

,id,title,production_budget,domestic_gross,worldwide_gross,release_year,genre,Review_counts,Freshness_score,profit,Profit,ROI,Domestic_vs_Worldwide_Ratio,Release_Month,Day_of_Week
5934,77,The Mongol King,7000,900,900,2004,Comedy|Drama,183.0,0.360656,-6100,-6100,-0.871429,1.0,12,Friday
5935,78,Red 11,7000,0,0,2018,NaN,NaN,NaN,-7000,-7000,-1.000000,NaN,12,Monday
5937,80,Return to the Land of Wonders,5000,1338,1338,2005,Action and Adventure|Art House and Internation...,15.0,0.866667,-3662,-3662,-0.732400,1.0,7,Wednesday
5938,81,A Plague So Pleasant,1400,0,0,2015,NaN,NaN,NaN,-1400,-1400,-1.000000,NaN,9,Tuesday
5939,82,My Date With Drew,1100,181041,181041,2005,Comedy|Mystery and Suspense|Science Fiction an...,102.0,0.852941,179941,179941,163.582727,1.0,8,Friday

### Director and Writer Metrics

In [559]:
review_metrics = rt_reviews_clean_df.groupby('id').agg(
    review_count=('fresh', 'count'),
    freshness_score=('fresh', lambda x: (x == 'fresh').sum() / len(x))
).reset_index()

In [564]:
# Merge review metrics with director and writer
review_metrics_full = pd.merge(rt_combined_df[['id', 'director', 'writer']], review_metrics, on='id', how='left')
review_metrics_full

,id,director,writer,review_count,freshness_score
0,1,William Friedkin,Ernest Tidyman,NaN,NaN
1,3,David Cronenberg,David Cronenberg|Don DeLillo,163.0,0.631902
2,5,Allison Anders,Allison Anders,23.0,0.782609
3,6,Barry Levinson,Paul Attanasio|Michael Crichton,57.0,0.561404
4,7,Rodney Bennett,Giles Cooper,NaN,NaN
...,...,...,...,...,...
1555,1996,Unknown,Unknown,143.0,0.671329
1556,1997,Steve Barron,Terry Turner|Tom Davis|Dan Aykroyd|Bonnie Turner,28.0,0.357143
1557,1998,Gordon Douglas,Unknown,2.0,1.000000
1558,1999,David Mickey Evans,David Mickey Evans|Robert Gunter,46.0,0.586957
1559,2000,Unknown,Luc Besson,38.0,0.473684

In [565]:
# Group by director
director_metrics = review_metrics_full.groupby('director').agg(
    director_avg_freshness=('freshness_score', 'mean'),
    director_avg_reviews=('review_count', 'mean'),
    director_movie_count=('id', 'count')
).reset_index()

# Group by writer
writer_metrics = review_metrics_full.groupby('writer').agg(
    writer_avg_freshness=('freshness_score', 'mean'),
    writer_avg_reviews=('review_count', 'mean'),
    writer_movie_count=('id', 'count')
).reset_index()

In [566]:
director_metrics

,director,director_avg_freshness,director_avg_reviews,director_movie_count
0,Abel Ferrara,0.293750,10.5,2
1,Adam Ravetch|Sarah Robertson,0.612903,93.0,1
2,Adam Shankman,0.044118,68.0,1
3,Adam Silver|Ben Hayflick,NaN,NaN,1
4,Aditya Chopra,NaN,NaN,1
...,...,...,...,...
1121,Youssef Delara,0.600000,5.0,1
1122,Yves Simoneau,0.333333,6.0,1
1123,Zak Penn,NaN,NaN,1
1124,Zeresenay Berhane Mehari,0.851852,27.0,1
1125,Zhang Jun Zhao,NaN,NaN,1

In [567]:
writer_metrics

,writer,writer_avg_freshness,writer_avg_reviews,writer_movie_count
0,Christina Trevino,NaN,NaN,1
1,Aaron Kandell|Jordan Kandell|David Branson Smi...,NaN,NaN,1
2,Aaron Latham|James Bridges,0.214286,14.0,1
3,Aaron Seltzer|Jason Friedberg,0.028571,35.0,1
4,Abby Kohn|Marc Silverstein|Dana Fox,NaN,NaN,1
...,...,...,...,...
1065,Yoav Shamir,0.842105,19.0,1
1066,Yoji Yamada|Ichiro Yamamoto|Emiko Hiramatsu,0.833333,18.0,1
1067,Zak Penn|Ernest Cline,0.618421,76.0,1
1068,Zenzo Matsumura,NaN,NaN,1
1069,Zeresenay Berhane Mehari,0.851852,27.0,1

In [568]:
# top directors avg reviews
top_directors_by_reviews = director_metrics.sort_values(by='director_avg_reviews', ascending=False).head(10)
top_directors_by_reviews

,director,director_avg_freshness,director_avg_reviews,director_movie_count
659,Martin McDonagh,0.911243,338.0,1
625,Luca Guadagnino,0.949091,275.0,1
709,Michel Hazanavicius,0.961538,260.0,1
493,Joel Coen|Ethan Coen,0.926923,260.0,1
76,Ava DuVernay,0.988372,258.0,1
727,Morten Tyldum,0.896414,251.0,1
678,Mel Gibson,0.485944,249.0,1
354,Guillermo del Toro,0.717300,237.0,1
1002,Steven Soderbergh,0.926724,232.0,1
935,Sam Mendes,0.795158,218.5,2

In [570]:
# top writers avg reviews
top_writers_by_reviews = writer_metrics.sort_values(by='writer_avg_reviews', ascending=False).head(10)
top_writers_by_reviews

,writer,writer_avg_freshness,writer_avg_reviews,writer_movie_count
632,Martin McDonagh,0.911243,338.0,1
423,James Ivory,0.949091,275.0,1
499,John Logan|Robert Wade|Neal Purvis,0.916031,262.0,1
672,Michel Hazanavicius,0.961538,260.0,1
302,Ethan Coen|Joel Coen,0.926923,260.0,1
759,Paul Webb,0.988372,258.0,1
789,Phyllis Nagy,0.941860,258.0,1
359,Graham Moore,0.896414,251.0,1
650,Mel Gibson|Benedict Fitzgerald,0.485944,249.0,1
770,Peter Jackson|Philippa Boyens|Guillermo del To...,0.621399,243.0,1