 ### 1. MERE DATA UNDERSTANDING

In [1]:
import pandas as pd

In [5]:
df_tn_budgets = pd.read_csv("../data/tn.movie_budgets.csv.gz", compression='gzip')
df_rt_reviews = pd.read_csv("../data/rt.reviews.tsv.gz", compression='gzip',sep='\t',low_memory=False,encoding='latin1')
df_rt_info = pd.read_csv("../data/rt.movie_info.tsv.gz", compression='gzip',sep='\t', low_memory=False)
df_bom_gross = pd.read_csv("../data/bom.movie_gross.csv.gz", compression='gzip')
df_tmdb_movies = pd.read_csv("../data/tmdb.movies.csv.gz", compression='gzip')

FileNotFoundError: [Errno 2] No such file or directory: '../data/bom.movie_gross.csv.gz'

#### 1.1 Data Understanding on tn.movie_budgets

In [602]:
print("\n--- 2. Initial Data Understanding (Raw Data) ---")

print("\n--- df_tn_budgets (Movie Budgets) ---")
df_tn_budgets.head()

--- 2. Initial Data Understanding (Raw Data) ---

--- df_tn_budgets (Movie Budgets) ---

,id,release_date,movie,production_budget,domestic_gross,worldwide_gross
0,1,"Dec 18, 2009",Avatar,"$425,000,000","$760,507,625","$2,776,345,279"
1,2,"May 20, 2011",Pirates of the Caribbean: On Stranger Tides,"$410,600,000","$241,063,875","$1,045,663,875"
2,3,"Jun 7, 2019",Dark Phoenix,"$350,000,000","$42,762,350","$149,762,350"
3,4,"May 1, 2015",Avengers: Age of Ultron,"$330,600,000","$459,005,868","$1,403,013,963"
4,5,"Dec 15, 2017",Star Wars Ep. VIII: The Last Jedi,"$317,000,000","$620,181,382","$1,316,721,747"

In [603]:
df_tn_budgets.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5782 entries, 0 to 5781
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 5782 non-null   int64
 1   release_date       5782 non-null   object
 2   movie              5782 non-null   object
 3   production_budget  5782 non-null   object
 4   domestic_gross     5782 non-null   object
 5   worldwide_gross    5782 non-null   object
dtypes: int64(1), object(5)
memory usage: 271.2+ KB

In [604]:
print("Checking Duplicates for Budget")
df_tn_budgets.duplicated().sum()

Checking Duplicates for Budget

0

In [605]:
print("-------------Missing values\n", df_tn_budgets.isnull().sum())

-------------Missing values
 id                   0
release_date         0
movie                0
production_budget    0
domestic_gross       0
worldwide_gross      0
dtype: int64

#### 1.2 Data Understanding for movies_info

In [606]:
print("\n--- df_rt_info (Rotten Tomatoes Movie Info) ---")
df_rt_info.head(10)

--- df_rt_info (Rotten Tomatoes Movie Info) ---

,id,synopsis,rating,genre,director,writer,theater_date,dvd_date,currency,box_office,runtime,studio
0,1,"This gritty, fast-paced, and innovative police...",R,Action and Adventure|Classics|Drama,William Friedkin,Ernest Tidyman,"Oct 9, 1971","Sep 25, 2001",NaN,NaN,104 minutes,NaN
1,3,"New York City, not-too-distant-future: Eric Pa...",R,Drama|Science Fiction and Fantasy,David Cronenberg,David Cronenberg|Don DeLillo,"Aug 17, 2012","Jan 1, 2013",$,"600,000",108 minutes,Entertainment One
2,5,Illeana Douglas delivers a superb performance ...,R,Drama|Musical and Performing Arts,Allison Anders,Allison Anders,"Sep 13, 1996","Apr 18, 2000",NaN,NaN,116 minutes,NaN
3,6,Michael Douglas runs afoul of a treacherous su...,R,Drama|Mystery and Suspense,Barry Levinson,Paul Attanasio|Michael Crichton,"Dec 9, 1994","Aug 27, 1997",NaN,NaN,128 minutes,NaN
4,7,NaN,NR,Drama|Romance,Rodney Bennett,Giles Cooper,NaN,NaN,NaN,NaN,200 minutes,NaN
5,8,The year is 1942. As the Allies unite overseas...,PG,Drama|Kids and Family,Jay Russell,Gail Gilchriest,"Mar 3, 2000","Jul 11, 2000",NaN,NaN,95 minutes,Warner Bros. Pictures
6,10,Some cast and crew from NBC's highly acclaimed...,PG-13,Comedy,Jake Kasdan,Mike White,"Jan 11, 2002","Jun 18, 2002",$,"41,032,915",82 minutes,Paramount Pictures
7,13,"Stewart Kane, an Irishman living in the Austra...",R,Drama,Ray Lawrence,Raymond Carver|Beatrix Christian,"Apr 27, 2006","Oct 2, 2007",$,"224,114",123 minutes,Sony Pictures Classics
8,14,"""Love Ranch"" is a bittersweet love story that ...",R,Drama,Taylor Hackford,Mark Jacobson,"Jun 30, 2010","Nov 9, 2010",$,"134,904",117 minutes,NaN
9,15,When a diamond expedition in the Congo is lost...,PG-13,Action and Adventure|Mystery and Suspense|Scie...,Frank Marshall,John Patrick Shanley,"Jun 9, 1995","Jul 27, 1999",NaN,NaN,108 minutes,NaN

In [607]:
 df_rt_info.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1560 entries, 0 to 1559
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            1560 non-null   int64
 1   synopsis      1498 non-null   object
 2   rating        1557 non-null   object
 3   genre         1552 non-null   object
 4   director      1361 non-null   object
 5   writer        1111 non-null   object
 6   theater_date  1201 non-null   object
 7   dvd_date      1201 non-null   object
 8   currency      340 non-null    object
 9   box_office    340 non-null    object
 10  runtime       1530 non-null   object
 11  studio        494 non-null    object
dtypes: int64(1), object(11)
memory usage: 146.4+ KB

In [608]:
print("Checking duplicates for movies_info")
df_rt_info.duplicated().sum()

Checking duplicates for movies_info

0

In [609]:
print("Missing values:\n", df_rt_info.isnull().sum())

Missing values:
 id                 0
synopsis          62
rating             3
genre              8
director         199
writer           449
theater_date     359
dvd_date         359
currency        1220
box_office      1220
runtime           30
studio          1066
dtype: int64

#### 1.3 Data Understanding for Bom_gross

In [610]:
print("\n--- df_bom_gross (Box Office Mojo Gross) ---")
df_bom_gross.head()

--- df_bom_gross (Box Office Mojo Gross) ---

,title,studio,domestic_gross,foreign_gross,year
0,Toy Story 3,BV,415000000.0,652000000,2010
1,Alice in Wonderland (2010),BV,334200000.0,691300000,2010
2,Harry Potter and the Deathly Hallows Part 1,WB,296000000.0,664300000,2010
3,Inception,WB,292600000.0,535700000,2010
4,Shrek Forever After,P/DW,238700000.0,513900000,2010

In [611]:
df_bom_gross.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3387 entries, 0 to 3386
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   title           3387 non-null   object
 1   studio          3382 non-null   object
 2   domestic_gross  3359 non-null   float64
 3   foreign_gross   2037 non-null   object
 4   year            3387 non-null   int64
dtypes: float64(1), int64(1), object(3)
memory usage: 132.4+ KB

In [612]:
print("Checking duplicates for bom_gross")
df_bom_gross.duplicated().sum()

Checking duplicates for bom_gross

0

In [613]:
print("Missing values:\n", df_bom_gross.isnull().sum())

Missing values:
 title                0
studio               5
domestic_gross      28
foreign_gross     1350
year                 0
dtype: int64

#### 1.4 Data Understanding for Reviews

In [614]:
print("\n--- df_rt_reviews (Rotten Tomatoes Reviews) ---")
df_rt_reviews.head(20)

--- df_rt_reviews (Rotten Tomatoes Reviews) ---

,id,review,rating,fresh,critic,top_critic,publisher,date
0,3,A distinctly gallows take on contemporary fina...,3/5,fresh,PJ Nabarro,0,Patrick Nabarro,"November 10, 2018"
1,3,It's an allegory in search of a meaning that n...,NaN,rotten,Annalee Newitz,0,io9.com,"May 23, 2018"
2,3,... life lived in a bubble in financial dealin...,NaN,fresh,Sean Axmaker,0,Stream on Demand,"January 4, 2018"
3,3,Continuing along a line introduced in last yea...,NaN,fresh,Daniel Kasman,0,MUBI,"November 16, 2017"
4,3,... a perverse twist on neorealism...,NaN,fresh,NaN,0,Cinema Scope,"October 12, 2017"
5,3,... Cronenberg's Cosmopolis expresses somethin...,NaN,fresh,Michelle Orange,0,Capital New York,"September 11, 2017"
6,3,"Quickly grows repetitive and tiresome, meander...",C,rotten,Eric D. Snider,0,EricDSnider.com,"July 17, 2013"
7,3,Cronenberg is not a director to be daunted by ...,2/5,rotten,Matt Kelemen,0,Las Vegas CityLife,"April 21, 2013"
8,3,"Cronenberg's cold, exacting precision and emot...",NaN,fresh,Sean Axmaker,0,Parallax View,"March 24, 2013"
9,3,Over and above its topical urgency or the bit ...,NaN,fresh,Kong Rithdee,0,Bangkok Post,"March 4, 2013"
10,3,"Cosmopolis"" is a hypnotic examination of our m...",NaN,fresh,Tim Grierson,0,Deadspin,"February 12, 2013"
11,3,"While not one of Cronenberg's stronger films, ...",B-,fresh,Emanuel Levy,0,EmanuelLevy.Com,"February 3, 2013"
12,3,Robert Pattinson works mighty hard to make Cos...,2/4,rotten,Christian Toto,0,Big Hollywood,"January 15, 2013"
13,3,The anger over the injustice of the financial ...,B,fresh,Robert Roten,0,Laramie Movie Scope,"January 7, 2013"
14,3,For those who like their Cronenberg thick and ...,3/4,fresh,Marty Mapes,0,Movie Habit,"October 20, 2012"
15,3,For better or worse - often both - Cosmopolis ...,3/5,fresh,Adam Ross,0,The Aristocrat,"September 27, 2012"
16,3,For one of the smartest films I've seen in a w...,4/5,fresh,Patrick Kolan,0,Shotgun Cinema,"September 26, 2012"
17,3,Its major problem is that it's not cinematic.,B,fresh,Dennis Schwartz,0,Ozus' World Movie Reviews,"September 25, 2012"
18,3,It's fascinating to watch Pattinson actually a...,2/4,rotten,Sean P. Means,0,Salt Lake Tribune,"September 14, 2012"
19,3,A black comedy as dry and deadpan as a bleache...,4/4,fresh,John Beifuss,0,"Commercial Appeal (Memphis, TN)","September 10, 2012"

In [615]:
df_rt_reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54432 entries, 0 to 54431
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          54432 non-null  int64
 1   review      48869 non-null  object
 2   rating      40915 non-null  object
 3   fresh       54432 non-null  object
 4   critic      51710 non-null  object
 5   top_critic  54432 non-null  int64
 6   publisher   54123 non-null  object
 7   date        54432 non-null  object
dtypes: int64(2), object(6)
memory usage: 3.3+ MB

In [616]:
print("Checking duplicates for reviews")
df_rt_reviews.duplicated().sum()

Checking duplicates for reviews

9

In [617]:
print("Missing values:\n", df_rt_reviews.isnull().sum())

Missing values:
 id                0
review         5563
rating        13517
fresh             0
critic         2722
top_critic        0
publisher       309
date              0
dtype: int64

#### 1.5 Data Understanding for tmdb

In [618]:
print("\n--- df_tmdb_movies (TMDB Movies) ---")
df_tmdb_movies.head()

--- df_tmdb_movies (TMDB Movies) ---

,Unnamed: 0,genre_ids,id,original_language,original_title,popularity,release_date,title,vote_average,vote_count
0,0,"[12, 14, 10751]",12444,en,Harry Potter and the Deathly Hallows: Part 1,33.533,2010-11-19,Harry Potter and the Deathly Hallows: Part 1,7.7,10788
1,1,"[14, 12, 16, 10751]",10191,en,How to Train Your Dragon,28.734,2010-03-26,How to Train Your Dragon,7.7,7610
2,2,"[12, 28, 878]",10138,en,Iron Man 2,28.515,2010-05-07,Iron Man 2,6.8,12368
3,3,"[16, 35, 10751]",862,en,Toy Story,28.005,1995-11-22,Toy Story,7.9,10174
4,4,"[28, 878, 12]",27205,en,Inception,27.920,2010-07-16,Inception,8.3,22186

In [619]:
df_tmdb_movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26517 entries, 0 to 26516
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         26517 non-null  int64
 1   genre_ids          26517 non-null  object
 2   id                 26517 non-null  int64
 3   original_language  26517 non-null  object
 4   original_title     26517 non-null  object
 5   popularity         26517 non-null  float64
 6   release_date       26517 non-null  object
 7   title              26517 non-null  object
 8   vote_average       26517 non-null  float64
 9   vote_count         26517 non-null  int64
dtypes: float64(2), int64(3), object(5)
memory usage: 2.0+ MB

In [620]:
print("Checking duplicates for tmdb")
df_tmdb_movies.duplicated().sum()

Checking duplicates for tmdb

0

In [621]:
print("Missing values:\n", df_tmdb_movies.isnull().sum())

Missing values:
 Unnamed: 0           0
genre_ids            0
id                   0
original_language    0
original_title       0
popularity           0
release_date         0
title                0
vote_average         0
vote_count           0
dtype: int64

### 2. MERE DATA CLEANING

#### Basically Data Type Conversions and Missing Value Handling

### 2.1 tn_movie_budget 
***Convert currency strings to numeric, and also parsing dates***

In [622]:
print("\nCleaning df_tn_budgets...")
for col in ['production_budget', 'domestic_gross', 'worldwide_gross']:
        if col in df_tn_budgets.columns and df_tn_budgets[col].dtype == 'object':
            df_tn_budgets[col] = df_tn_budgets[col].astype(str).str.replace('$', '', regex=False).str.replace(',', '', regex=False)
            df_tn_budgets[col] = pd.to_numeric(df_tn_budgets[col], errors='coerce')

Cleaning df_tn_budgets...

In [623]:
df_tn_budgets['release_date'] = pd.to_datetime(df_tn_budgets['release_date'], errors='coerce')

In [624]:
# Extract release year from tn
df_tn_budgets['release_year'] = df_tn_budgets['release_date'].dt.year

In [625]:
print("df_tn_budgets after cleaning:")
print()
df_tn_budgets.info()

df_tn_budgets after cleaning:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5782 entries, 0 to 5781
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 5782 non-null   int64
 1   release_date       5782 non-null   datetime64[ns]
 2   movie              5782 non-null   object
 3   production_budget  5782 non-null   int64
 4   domestic_gross     5782 non-null   int64
 5   worldwide_gross    5782 non-null   int64
 6   release_year       5782 non-null   int64
dtypes: datetime64[ns](1), int64(5), object(1)
memory usage: 316.3+ KB

### 2.2 bom_gross
***Convert currency strings to numeric, fill missing 'foreign_gross' with 0.***


***fill missing 'studio' with 'Uknown.***


***drop rows with missing 'domestic_gross***

In [626]:
print("\nCleaning df_bom_gross...")
for col in ['domestic_gross', 'foreign_gross']:
        if col in df_bom_gross.columns and df_bom_gross[col].dtype == 'object':
            df_bom_gross[col] = df_bom_gross[col].astype(str).str.replace('$', '', regex=False).str.replace(',', '', regex=False)
            df_bom_gross[col] = pd.to_numeric(df_bom_gross[col], errors='coerce')

Cleaning df_bom_gross...

In [627]:
df_bom_gross.drop(columns='foreign_gross', inplace=True)

In [628]:
if 'studio' in df_bom_gross.columns:
        initial_missing_studio = df_bom_gross['studio'].isnull().sum()
        df_bom_gross['studio'] = df_bom_gross['studio'].fillna('Unknown')
        print(f"Filled {initial_missing_studio} missing 'studio' values with 'Unknown'.")

Filled 5 missing 'studio' values with 'Unknown'.

In [629]:
if 'domestic_gross' in df_bom_gross.columns:
        initial_rows_bom_domestic = len(df_bom_gross)
        df_bom_gross.dropna(subset=['domestic_gross'], inplace=True)
        print(f"df_bom_gross: Dropped {initial_rows_bom_domestic - len(df_bom_gross)} rows due to missing 'domestic_gross'.")

df_bom_gross: Dropped 28 rows due to missing 'domestic_gross'.

In [630]:
print("df_bom_gross after cleaning:")
print()
df_bom_gross.info()

df_bom_gross after cleaning:

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3359 entries, 0 to 3386
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   title           3359 non-null   object
 1   studio          3359 non-null   object
 2   domestic_gross  3359 non-null   float64
 3   year            3359 non-null   int64
dtypes: float64(1), int64(1), object(2)
memory usage: 131.2+ KB

In [631]:
print("Missing values after cleaning:\n", df_bom_gross.isnull().sum())

Missing values after cleaning:
 title             0
studio            0
domestic_gross    0
year              0
dtype: int64

### 2.3 movies_info(rt_info)
***Convert 'box_office' to numeric, parse 'theater_date'***

***Convert 'runtime' to numeric and then fill missing***

In [632]:
print("\nCleaning df_rt_info...")
if 'box_office' in df_rt_info.columns and df_rt_info['box_office'].dtype == 'object':
        df_rt_info['box_office'] = df_rt_info['box_office'].astype(str).str.replace('$', '', regex=False).str.replace(',', '', regex=False)
        df_rt_info['box_office'] = pd.to_numeric(df_rt_info['box_office'], errors='coerce')
if 'theater_date' in df_rt_info.columns:
        df_rt_info['theater_date'] = pd.to_datetime(df_rt_info['theater_date'], errors='coerce')

Cleaning df_rt_info...

In [633]:
for col in ['synopsis', 'rating', 'genre', 'director', 'writer', 'studio']:
        if col in df_rt_info.columns:
            initial_missing_count = df_rt_info[col].isnull().sum()
            if initial_missing_count > 0:
                df_rt_info[col] = df_rt_info[col].fillna('Unknown')
                print(f"Filled {initial_missing_count} missing '{col}' values with 'Unknown'.")

Filled 62 missing 'synopsis' values with 'Unknown'.
Filled 3 missing 'rating' values with 'Unknown'.
Filled 8 missing 'genre' values with 'Unknown'.
Filled 199 missing 'director' values with 'Unknown'.
Filled 449 missing 'writer' values with 'Unknown'.
Filled 1066 missing 'studio' values with 'Unknown'.

In [634]:
if 'runtime' in df_rt_info.columns:
        # First, remove " minutes" string if present
        if df_rt_info['runtime'].dtype == 'object':
            df_rt_info['runtime'] = df_rt_info['runtime'].astype(str).str.replace(' minutes', '', regex=False)
        # Convert to numeric, coercing errors (e.g., non-numeric strings) to NaN
        df_rt_info['runtime'] = pd.to_numeric(df_rt_info['runtime'], errors='coerce')
        initial_missing_runtime = df_rt_info['runtime'].isnull().sum()
        if initial_missing_runtime > 0:
            median_runtime = df_rt_info['runtime'].median()
            df_rt_info['runtime'] = df_rt_info['runtime'].fillna(median_runtime)
            print(f"Filled {initial_missing_runtime} missing 'runtime' values with median ({median_runtime}).")

Filled 30 missing 'runtime' values with median (100.0).

In [635]:
print("df_rt_info after cleaning:")
df_rt_info.info()

df_rt_info after cleaning:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1560 entries, 0 to 1559
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            1560 non-null   int64
 1   synopsis      1560 non-null   object
 2   rating        1560 non-null   object
 3   genre         1560 non-null   object
 4   director      1560 non-null   object
 5   writer        1560 non-null   object
 6   theater_date  1201 non-null   datetime64[ns]
 7   dvd_date      1201 non-null   object
 8   currency      340 non-null    object
 9   box_office    340 non-null    float64
 10  runtime       1560 non-null   float64
 11  studio        1560 non-null   object
dtypes: datetime64[ns](1), float64(2), int64(1), object(8)
memory usage: 146.4+ KB

In [636]:
print("Missing values after cleaning:\n", df_rt_info.isnull().sum())

Missing values after cleaning:
 id                 0
synopsis           0
rating             0
genre              0
director           0
writer             0
theater_date     359
dvd_date         359
currency        1220
box_office      1220
runtime            0
studio             0
dtype: int64

***For the theatre and dvd:These are extra date columns that aren't critical. We already have complete and reliable release date info from release_date_tn (in tn.movie_budgets)***

***For the currency and box office:These are secondary financial details from Rotten Tomatoes. We don’t rely on them for final financial analysis. Instead, we use more complete and prioritized data from tn.movie_budgets and bom.movie_gross for Worldwide_Gross***

### 2.4 Cleaning rt_reviews
***Parsing date.***

***Fill missing 'review' text with a placeholder***

***Fill missing 'rating' with median***

***Fill missing 'critic' and 'publisher' with 'Unknown'***

In [637]:
print("\nCleaning df_rt_reviews...")
if 'date' in df_rt_reviews.columns:
        df_rt_reviews['date'] = pd.to_datetime(df_rt_reviews['date'], errors='coerce')

Cleaning df_rt_reviews...

In [638]:
if 'review' in df_rt_reviews.columns:
        initial_missing_review = df_rt_reviews['review'].isnull().sum()
        if initial_missing_review > 0:
            df_rt_reviews['review'] = df_rt_reviews['review'].fillna('No Review Text')
            print(f"Filled {initial_missing_review} missing 'review' values with 'No Review Text'.")

Filled 5563 missing 'review' values with 'No Review Text'.

In [639]:
df_rt_reviews[df_rt_reviews.duplicated()]

,id,review,rating,fresh,critic,top_critic,publisher,date
8129,304,"Friends With Kids is a smart, witty and potty-...",NaN,fresh,NaN,0,Liverpool Echo,2012-06-29
14575,581,No Review Text,4.5/5,fresh,NaN,0,Film Threat,2005-12-06
26226,1055,No Review Text,4/5,fresh,NaN,0,Film Threat,2005-12-06
35162,1368,No Review Text,2/5,rotten,NaN,0,Film Threat,2005-12-06
35166,1368,No Review Text,2/5,rotten,NaN,0,Film Threat,2002-12-08
40567,1535,No Review Text,2/5,rotten,NaN,0,Film Threat,2005-12-06
42381,1598,"This tired, neutered action thriller won't cau...",2/5,rotten,NaN,0,Empire Magazine,2008-11-14
49487,1843,No Review Text,0.5/5,rotten,NaN,0,Film Threat,2005-12-06
49492,1843,No Review Text,0.5/5,rotten,NaN,0,Film Threat,2002-12-08

In [640]:
if all(col in df_rt_reviews.columns for col in ['id', 'review', 'critic','publisher', 'date']):
        initial_rows_rt_reviews = len(df_rt_reviews)
        df_rt_reviews.drop_duplicates(subset=['id', 'review', 'critic','publisher', 'date'])
        print(f"df_rt_reviews: Removed {initial_rows_rt_reviews - len(df_rt_reviews)} duplicates based on 'id', 'review','publisher', 'critic', and 'date'.")
else:
        print("df_rt_reviews: Skipping duplicate check due to missing 'id', 'review', 'critic', or 'date' columns.")

df_rt_reviews: Removed 0 duplicates based on 'id', 'review','publisher', 'critic', and 'date'.

In [641]:
df_rt_reviews.drop(columns='rating', inplace=True)

In [642]:
df_rt_reviews.fresh.value_counts()

fresh     33035
rotten    21397
Name: fresh, dtype: int64

In [643]:
for col in ['critic', 'publisher']:
        if col in df_rt_reviews.columns:
            initial_missing_count = df_rt_reviews[col].isnull().sum()
            if initial_missing_count > 0:
                df_rt_reviews[col] = df_rt_reviews[col].fillna('Unknown ' + col.capitalize())
                print(f"Filled {initial_missing_count} missing '{col}' values with 'Unknown {col.capitalize()}'.")

Filled 2722 missing 'critic' values with 'Unknown Critic'.
Filled 309 missing 'publisher' values with 'Unknown Publisher'.

In [644]:
print("df_rt_reviews after cleaning:")
print()
print(df_rt_reviews.info())
print()
print(f"Duplicates:", df_rt_reviews.duplicated().sum())

df_rt_reviews after cleaning:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54432 entries, 0 to 54431
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          54432 non-null  int64
 1   review      54432 non-null  object
 2   fresh       54432 non-null  object
 3   critic      54432 non-null  object
 4   top_critic  54432 non-null  int64
 5   publisher   54432 non-null  object
 6   date        54432 non-null  datetime64[ns]
dtypes: datetime64[ns](1), int64(2), object(4)
memory usage: 2.9+ MB
None

Duplicates: 25

In [645]:
print("Missing values after cleaning:\n", df_rt_reviews.isnull().sum())

Missing values after cleaning:
 id            0
review        0
fresh         0
critic        0
top_critic    0
publisher     0
date          0
dtype: int64

### 2.5 tmbd_movies Cleaning
***Parse 'release_date' column***

In [646]:
df_tmdb_movies['release_date'] = pd.to_datetime(df_tmdb_movies['release_date'], errors='coerce')
df_tmdb_movies['release_year'] = df_tmdb_movies['release_date'].dt.year

In [647]:
print("df_tmdb_movies after cleaning:")
print()
df_tmdb_movies.info()

df_tmdb_movies after cleaning:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26517 entries, 0 to 26516
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         26517 non-null  int64
 1   genre_ids          26517 non-null  object
 2   id                 26517 non-null  int64
 3   original_language  26517 non-null  object
 4   original_title     26517 non-null  object
 5   popularity         26517 non-null  float64
 6   release_date       26517 non-null  datetime64[ns]
 7   title              26517 non-null  object
 8   vote_average       26517 non-null  float64
 9   vote_count         26517 non-null  int64
 10  release_year       26517 non-null  int64
dtypes: datetime64[ns](1), float64(2), int64(4), object(4)
memory usage: 2.2+ MB

In [648]:
print("Missing values after cleaning:\n", df_tmdb_movies.isnull().sum())

Missing values after cleaning:
 Unnamed: 0           0
genre_ids            0
id                   0
original_language    0
original_title       0
popularity           0
release_date         0
title                0
vote_average         0
vote_count           0
release_year         0
dtype: int64

### 3. Feature Engineering
*** Calculate Review_Count from df_rt_reviews***

In [649]:
# Compute Review_Count and Freshness_Score
review_counts = df_rt_reviews.groupby('id').agg(
    Review_Count=('fresh', 'count'),
    Freshness_Score=('fresh', lambda x: (x == 'fresh').sum() / len(x))
).reset_index()

***Merging Reviews and Info***

In [650]:
df_rt_combined = pd.merge(df_rt_info, review_counts, on='id', how='left')
df_rt_combined

,id,synopsis,rating,genre,director,writer,theater_date,dvd_date,currency,box_office,runtime,studio,Review_Count,Freshness_Score
0,1,"This gritty, fast-paced, and innovative police...",R,Action and Adventure|Classics|Drama,William Friedkin,Ernest Tidyman,1971-10-09,"Sep 25, 2001",NaN,NaN,104.0,Unknown,NaN,NaN
1,3,"New York City, not-too-distant-future: Eric Pa...",R,Drama|Science Fiction and Fantasy,David Cronenberg,David Cronenberg|Don DeLillo,2012-08-17,"Jan 1, 2013",$,600000.0,108.0,Entertainment One,163.0,0.631902
2,5,Illeana Douglas delivers a superb performance ...,R,Drama|Musical and Performing Arts,Allison Anders,Allison Anders,1996-09-13,"Apr 18, 2000",NaN,NaN,116.0,Unknown,23.0,0.782609
3,6,Michael Douglas runs afoul of a treacherous su...,R,Drama|Mystery and Suspense,Barry Levinson,Paul Attanasio|Michael Crichton,1994-12-09,"Aug 27, 1997",NaN,NaN,128.0,Unknown,57.0,0.561404
4,7,Unknown,NR,Drama|Romance,Rodney Bennett,Giles Cooper,NaT,NaN,NaN,NaN,200.0,Unknown,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1555,1996,Forget terrorists or hijackers -- there's a ha...,R,Action and Adventure|Horror|Mystery and Suspense,Unknown,Unknown,2006-08-18,"Jan 2, 2007",$,33886034.0,106.0,New Line Cinema,143.0,0.671329
1556,1997,The popular Saturday Night Live sketch was exp...,PG,Comedy|Science Fiction and Fantasy,Steve Barron,Terry Turner|Tom Davis|Dan Aykroyd|Bonnie Turner,1993-07-23,"Apr 17, 2001",NaN,NaN,88.0,Paramount Vantage,28.0,0.357143
1557,1998,"Based on a novel by Richard Powell, when the l...",G,Classics|Comedy|Drama|Musical and Performing Arts,Gordon Douglas,Unknown,1962-01-01,"May 11, 2004",NaN,NaN,111.0,Unknown,2.0,1.000000
1558,1999,The Sandlot is a coming-of-age story about a g...,PG,Comedy|Drama|Kids and Family|Sports and Fitness,David Mickey Evans,David Mickey Evans|Robert Gunter,1993-04-01,"Jan 29, 2002",NaN,NaN,101.0,Unknown,46.0,0.586957
1559,2000,"Suspended from the force, Paris cop Hubert is ...",R,Action and Adventure|Art House and Internation...,Unknown,Luc Besson,2001-09-27,"Feb 11, 2003",NaN,NaN,94.0,Columbia Pictures,38.0,0.473684

***Merging tmdb and tn_budgets***

In [651]:
#for differentiation I renamed the 'title' to 'tmdb_title' to avoid problems when merging
df_tmdb_movies.rename(columns={'title': 'tmdb_title'}, inplace=True)

In [652]:
#Renamed movie in tn_budget for easy understanding when merging with tmdb
df_tn_budgets.rename(columns={'movie': 'title'}, inplace=True)

In [653]:
# Merge tn and tmdb on title and release year
merged = pd.merge(df_tn_budgets, df_tmdb_movies, left_on=['title', 'release_year'], right_on=['tmdb_title', 'release_year'], how='left')
merged

,id_x,release_date_x,title,production_budget,domestic_gross,worldwide_gross,release_year,Unnamed: 0,genre_ids,id_y,original_language,original_title,popularity,release_date_y,tmdb_title,vote_average,vote_count
0,1,2009-12-18,Avatar,425000000,760507625,2776345279,2009,6.0,"[28, 12, 14, 878]",19995.0,en,Avatar,26.526,2009-12-18,Avatar,7.4,18676.0
1,2,2011-05-20,Pirates of the Caribbean: On Stranger Tides,410600000,241063875,1045663875,2011,2470.0,"[12, 28, 14]",1865.0,en,Pirates of the Caribbean: On Stranger Tides,30.579,2011-05-20,Pirates of the Caribbean: On Stranger Tides,6.4,8571.0
2,3,2019-06-07,Dark Phoenix,350000000,42762350,149762350,2019,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
3,4,2015-05-01,Avengers: Age of Ultron,330600000,459005868,1403013963,2015,14169.0,"[28, 12, 878]",99861.0,en,Avengers: Age of Ultron,44.383,2015-05-01,Avengers: Age of Ultron,7.3,13457.0
4,5,2017-12-15,Star Wars Ep. VIII: The Last Jedi,317000000,620181382,1316721747,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5935,78,2018-12-31,Red 11,7000,0,0,2018,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
5936,79,1999-04-02,Following,6000,48482,240495,1999,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
5937,80,2005-07-13,Return to the Land of Wonders,5000,1338,1338,2005,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
5938,81,2015-09-29,A Plague So Pleasant,1400,0,0,2015,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
5939,82,2005-08-05,My Date With Drew,1100,181041,181041,2005,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN

***Merging the df_rt_combined and merged for a final dataframe***

In [654]:
# Rename id_x for merging
merged.rename(columns={'id_x': 'id'}, inplace=True)

In [655]:
# Merge with RT info
merged = pd.merge(merged, df_rt_combined[['id', 'genre', 'rating', 'Review_Count', 'Freshness_Score']], on='id', how='left')
merged.columns

Index(['id', 'release_date_x', 'title', 'production_budget', 'domestic_gross',
       'worldwide_gross', 'release_year', 'Unnamed: 0', 'genre_ids', 'id_y',
       'original_language', 'original_title', 'popularity', 'release_date_y',
       'tmdb_title', 'vote_average', 'vote_count', 'genre', 'rating',
       'Review_Count', 'Freshness_Score'],
      dtype='object')

### Final feature Engineering

In [656]:
# Financial and temporal features
merged['Profit'] = merged['worldwide_gross'] - merged['production_budget']
merged['ROI'] = merged['Profit'] / merged['production_budget']
merged['Domestic_vs_Worldwide_Ratio'] = merged['domestic_gross'] / merged['worldwide_gross']
merged['Release_Month'] = merged['release_date_x'].dt.month
merged['Day_of_Week'] = merged['release_date_x'].dt.day_name()
merged['foreign_gross'] = merged['worldwide_gross'] - merged['domestic_gross']

In [657]:
merged.head()

,id,release_date_x,title,production_budget,domestic_gross,worldwide_gross,release_year,Unnamed: 0,genre_ids,id_y,...,genre,rating,Review_Count,Freshness_Score,Profit,ROI,Domestic_vs_Worldwide_Ratio,Release_Month,Day_of_Week,foreign_gross
0,1,2009-12-18,Avatar,425000000,760507625,2776345279,2009,6.0,"[28, 12, 14, 878]",19995.0,...,Action and Adventure|Classics|Drama,R,NaN,NaN,2351345279,5.532577,0.273924,12,Friday,2015837654
1,2,2011-05-20,Pirates of the Caribbean: On Stranger Tides,410600000,241063875,1045663875,2011,2470.0,"[12, 28, 14]",1865.0,...,NaN,NaN,NaN,NaN,635063875,1.546673,0.230537,5,Friday,804600000
2,3,2019-06-07,Dark Phoenix,350000000,42762350,149762350,2019,NaN,NaN,NaN,...,Drama|Science Fiction and Fantasy,R,163.0,0.631902,-200237650,-0.572108,0.285535,6,Friday,107000000
3,4,2015-05-01,Avengers: Age of Ultron,330600000,459005868,1403013963,2015,14169.0,"[28, 12, 878]",99861.0,...,NaN,NaN,NaN,NaN,1072413963,3.243841,0.327157,5,Friday,944008095
4,5,2017-12-15,Star Wars Ep. VIII: The Last Jedi,317000000,620181382,1316721747,2017,NaN,NaN,NaN,...,Drama|Musical and Performing Arts,R,23.0,0.782609,999721747,3.153696,0.471004,12,Friday,696540365

In [659]:
merged.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5940 entries, 0 to 5939
Data columns (total 27 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   id                           5940 non-null   int64
 1   release_date_x               5940 non-null   datetime64[ns]
 2   title                        5940 non-null   object
 3   production_budget            5940 non-null   int64
 4   domestic_gross               5940 non-null   int64
 5   worldwide_gross              5940 non-null   int64
 6   release_year                 5940 non-null   int64
 7   Unnamed: 0                   1758 non-null   float64
 8   genre_ids                    1758 non-null   object
 9   id_y                         1758 non-null   float64
 10  original_language            1758 non-null   object
 11  original_title               1758 non-null   object
 12  popularity                   1758 non-null   float64
 13  release_date_y               1758 non-null   datetime64[ns]
 14  tmdb_title                   1758 non-null   object
 15  vote_average                 1758 non-null   float64
 16  vote_count                   1758 non-null   float64
 17  genre                        4809 non-null   object
 18  rating                       4809 non-null   object
 19  Review_Count                 3509 non-null   float64
 20  Freshness_Score              3509 non-null   float64
 21  Profit                       5940 non-null   int64
 22  ROI                          5940 non-null   float64
 23  Domestic_vs_Worldwide_Ratio  5570 non-null   float64
 24  Release_Month                5940 non-null   int64
 25  Day_of_Week                  5940 non-null   object
 26  foreign_gross                5940 non-null   int64
dtypes: datetime64[ns](2), float64(9), int64(8), object(8)
memory usage: 1.3+ MB

In [660]:
# Drop suffix columns and low-value metadata
redundant_cols = [col for col in merged.columns if col.endswith('_x') or col.endswith('_y')]
low_value_cols = [
    'id_y', 'tmdb_title', 'original_title', 'original_language', 'currency',
    'dvd_date', 'release_date_y', 'release_date_x', 'rating', 'writer',
    'synopsis', 'theater_date', 'popularity', 'vote_count', 'vote_average','Unnamed: 0','genre_ids'
]
drop_columns = list(set(redundant_cols + low_value_cols))
merged.drop(columns=drop_columns, errors='ignore', inplace=True)
merged.head()

,id,title,production_budget,domestic_gross,worldwide_gross,release_year,genre,Review_Count,Freshness_Score,Profit,ROI,Domestic_vs_Worldwide_Ratio,Release_Month,Day_of_Week,foreign_gross
0,1,Avatar,425000000,760507625,2776345279,2009,Action and Adventure|Classics|Drama,NaN,NaN,2351345279,5.532577,0.273924,12,Friday,2015837654
1,2,Pirates of the Caribbean: On Stranger Tides,410600000,241063875,1045663875,2011,NaN,NaN,NaN,635063875,1.546673,0.230537,5,Friday,804600000
2,3,Dark Phoenix,350000000,42762350,149762350,2019,Drama|Science Fiction and Fantasy,163.0,0.631902,-200237650,-0.572108,0.285535,6,Friday,107000000
3,4,Avengers: Age of Ultron,330600000,459005868,1403013963,2015,NaN,NaN,NaN,1072413963,3.243841,0.327157,5,Friday,944008095
4,5,Star Wars Ep. VIII: The Last Jedi,317000000,620181382,1316721747,2017,Drama|Musical and Performing Arts,23.0,0.782609,999721747,3.153696,0.471004,12,Friday,696540365

In [661]:
merged.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5940 entries, 0 to 5939
Data columns (total 15 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   id                           5940 non-null   int64
 1   title                        5940 non-null   object
 2   production_budget            5940 non-null   int64
 3   domestic_gross               5940 non-null   int64
 4   worldwide_gross              5940 non-null   int64
 5   release_year                 5940 non-null   int64
 6   genre                        4809 non-null   object
 7   Review_Count                 3509 non-null   float64
 8   Freshness_Score              3509 non-null   float64
 9   Profit                       5940 non-null   int64
 10  ROI                          5940 non-null   float64
 11  Domestic_vs_Worldwide_Ratio  5570 non-null   float64
 12  Release_Month                5940 non-null   int64
 13  Day_of_Week                  5940 non-null   object
 14  foreign_gross                5940 non-null   int64
dtypes: float64(4), int64(8), object(3)
memory usage: 742.5+ KB

### Director and Writer Metrics

In [663]:
review_metrics = df_rt_reviews.groupby('id').agg(
    review_count=('fresh', 'count'),
    freshness_score=('fresh', lambda x: (x == 'fresh').sum() / len(x))
).reset_index()

In [664]:
# Merge review metrics with director and writer
review_metrics_full = pd.merge(df_rt_info[['id', 'director', 'writer']], review_metrics, on='id', how='left')

In [665]:
# Group by director
director_metrics = review_metrics_full.groupby('director').agg(
    director_avg_freshness=('freshness_score', 'mean'),
    director_avg_reviews=('review_count', 'mean'),
    director_movie_count=('id', 'count')
).reset_index()

# Group by writer
writer_metrics = review_metrics_full.groupby('writer').agg(
    writer_avg_freshness=('freshness_score', 'mean'),
    writer_avg_reviews=('review_count', 'mean'),
    writer_movie_count=('id', 'count')
).reset_index()

In [666]:
director_metrics

,director,director_avg_freshness,director_avg_reviews,director_movie_count
0,Abel Ferrara,0.293750,10.5,2
1,Adam Ravetch|Sarah Robertson,0.612903,93.0,1
2,Adam Shankman,0.044118,68.0,1
3,Adam Silver|Ben Hayflick,NaN,NaN,1
4,Aditya Chopra,NaN,NaN,1
...,...,...,...,...
1121,Youssef Delara,0.600000,5.0,1
1122,Yves Simoneau,0.333333,6.0,1
1123,Zak Penn,NaN,NaN,1
1124,Zeresenay Berhane Mehari,0.851852,27.0,1
1125,Zhang Jun Zhao,NaN,NaN,1

In [667]:
# Merge director/writer into main dataset
# merged = pd.merge(merged, df_rt_info[['id', 'director', 'writer']], on='id', how='left')
# merged = pd.merge(merged, director_metrics, on='director', how='left')
# merged = pd.merge(merged, writer_metrics, on='writer', how='left')

In [668]:
merged

,id,title,production_budget,domestic_gross,worldwide_gross,release_year,genre,Review_Count,Freshness_Score,Profit,ROI,Domestic_vs_Worldwide_Ratio,Release_Month,Day_of_Week,foreign_gross
0,1,Avatar,425000000,760507625,2776345279,2009,Action and Adventure|Classics|Drama,NaN,NaN,2351345279,5.532577,0.273924,12,Friday,2015837654
1,2,Pirates of the Caribbean: On Stranger Tides,410600000,241063875,1045663875,2011,NaN,NaN,NaN,635063875,1.546673,0.230537,5,Friday,804600000
2,3,Dark Phoenix,350000000,42762350,149762350,2019,Drama|Science Fiction and Fantasy,163.0,0.631902,-200237650,-0.572108,0.285535,6,Friday,107000000
3,4,Avengers: Age of Ultron,330600000,459005868,1403013963,2015,NaN,NaN,NaN,1072413963,3.243841,0.327157,5,Friday,944008095
4,5,Star Wars Ep. VIII: The Last Jedi,317000000,620181382,1316721747,2017,Drama|Musical and Performing Arts,23.0,0.782609,999721747,3.153696,0.471004,12,Friday,696540365
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5935,78,Red 11,7000,0,0,2018,NaN,NaN,NaN,-7000,-1.000000,NaN,12,Monday,0
5936,79,Following,6000,48482,240495,1999,Action and Adventure|Drama|Mystery and Suspense,18.0,0.611111,234495,39.082500,0.201593,4,Friday,192013
5937,80,Return to the Land of Wonders,5000,1338,1338,2005,Action and Adventure|Art House and Internation...,15.0,0.866667,-3662,-0.732400,1.000000,7,Wednesday,0
5938,81,A Plague So Pleasant,1400,0,0,2015,NaN,NaN,NaN,-1400,-1.000000,NaN,9,Tuesday,0
5939,82,My Date With Drew,1100,181041,181041,2005,Comedy|Mystery and Suspense|Science Fiction an...,102.0,0.852941,179941,163.582727,1.000000,8,Friday,0

In [669]:
top_directors_by_reviews = director_metrics.sort_values(by='director_avg_reviews', ascending=False).head(10)
top_directors_by_reviews

,director,director_avg_freshness,director_avg_reviews,director_movie_count
659,Martin McDonagh,0.911243,338.0,1
625,Luca Guadagnino,0.949091,275.0,1
709,Michel Hazanavicius,0.961538,260.0,1
493,Joel Coen|Ethan Coen,0.926923,260.0,1
76,Ava DuVernay,0.988372,258.0,1
727,Morten Tyldum,0.896414,251.0,1
678,Mel Gibson,0.485944,249.0,1
354,Guillermo del Toro,0.717300,237.0,1
1002,Steven Soderbergh,0.926724,232.0,1
935,Sam Mendes,0.795158,218.5,2

In [670]:
top_writers_by_reviews = writer_metrics.sort_values(by='writer_avg_reviews', ascending=False).head(10)
top_writers_by_reviews

,writer,writer_avg_freshness,writer_avg_reviews,writer_movie_count
632,Martin McDonagh,0.911243,338.0,1
423,James Ivory,0.949091,275.0,1
499,John Logan|Robert Wade|Neal Purvis,0.916031,262.0,1
672,Michel Hazanavicius,0.961538,260.0,1
302,Ethan Coen|Joel Coen,0.926923,260.0,1
759,Paul Webb,0.988372,258.0,1
789,Phyllis Nagy,0.941860,258.0,1
359,Graham Moore,0.896414,251.0,1
650,Mel Gibson|Benedict Fitzgerald,0.485944,249.0,1
770,Peter Jackson|Philippa Boyens|Guillermo del To...,0.621399,243.0,1

In [671]:
merged.isnull().sum()

id                                0
title                             0
production_budget                 0
domestic_gross                    0
worldwide_gross                   0
release_year                      0
genre                          1131
Review_Count                   2431
Freshness_Score                2431
Profit                            0
ROI                               0
Domestic_vs_Worldwide_Ratio     370
Release_Month                     0
Day_of_Week                       0
foreign_gross                     0
dtype: int64